import {describe,expect,it} from "vitest";
import {GET,POST} from "../app/api/cases/route";
import {PATCH} from "../app/api/cases/[sessionId]/route";

describe("case API isolation",()=>{
 it("lists only public case metadata",async()=>{const response=await GET(new Request("http://local/api/cases")),body=await response.json();expect(body.cases.length).toBeGreaterThanOrEqual(8);expect(body.cases[0]).not.toHaveProperty("hiddenFacts");expect(body.cases[0]).not.toHaveProperty("calculations");expect(response.headers.get("set-cookie")).toMatch(/HttpOnly/)});
 it("never returns the frozen answer key when starting a case",async()=>{const response=await POST(new Request("http://local/api/cases",{method:"POST",body:JSON.stringify({caseId:"northline",mode:"strict"})}));const text=await response.text();expect(response.status).toBe(201);expect(text).not.toContain("2160000");expect(text).not.toContain("Incremental contribution")});
 it("validates mode and case identity",async()=>{const badMode=await POST(new Request("http://local/api/cases",{method:"POST",body:JSON.stringify({caseId:"northline",mode:"easy"})}));expect(badMode.status).toBe(400);const missing=await POST(new Request("http://local/api/cases",{method:"POST",body:JSON.stringify({caseId:"missing",mode:"practice"})}));expect(missing.status).toBe(404)});
 it("masks readiness holdouts and prevents use in training modes",async()=>{const listing=await GET(new Request("http://local/api/cases")),body=await listing.json(),holdout=body.cases.find((x:{poolRole:string})=>x.poolRole==="READINESS_HOLDOUT");expect(holdout.title).toBe("Unseen readiness assessment");expect(JSON.stringify(holdout)).not.toContain("Public sector");expect((await POST(new Request("http://local/api/cases",{method:"POST",body:JSON.stringify({caseId:holdout.id,mode:"practice"})}))).status).toBe(403);expect((await POST(new Request("http://local/api/cases",{method:"POST",body:JSON.stringify({caseId:holdout.id,mode:"readiness"})}))).status).toBe(201)});
 it("binds sessions to the server-issued identity",async()=>{const started=await POST(new Request("http://local/api/cases",{method:"POST",body:JSON.stringify({caseId:"northline",mode:"practice"})})),cookie=started.headers.get("set-cookie")!,body=await started.json();const denied=await PATCH(new Request(`http://local/api/cases/${body.view.sessionId}`,{method:"PATCH",body:JSON.stringify({type:"request-hint"})}),{params:Promise.resolve({sessionId:body.view.sessionId})});expect(denied.status).toBe(404);const allowed=await PATCH(new Request(`http://local/api/cases/${body.view.sessionId}`,{method:"PATCH",headers:{cookie},body:JSON.stringify({type:"request-hint"})}),{params:Promise.resolve({sessionId:body.view.sessionId})});expect(allowed.status).toBe(200)});
 it("rejects cross-origin and oversized mutations",async()=>{const cross=await POST(new Request("http://local/api/cases",{method:"POST",headers:{origin:"https://attacker.example"},body:JSON.stringify({caseId:"northline",mode:"practice"})}));expect(cross.status).toBe(400);const large=await POST(new Request("http://local/api/cases",{method:"POST",headers:{"content-length":"20000"},body:"{}"}));expect(large.status).toBe(400)});
});
