import { describe,expect,it } from "vitest";
import { brainstormExercises, exhibitExercises, exerciseCatalog, mentalMathExercises, quantSetupExercises, structureExercises, synthesisExercises } from "./catalog";
import { qualitativeEvaluationSchema, reliabilityWeight, shouldSecondEvaluate } from "./evaluation";
import { startCase } from "./domain";
import { cases } from "./seed";
import { TextInterviewTransport, VoiceInterviewTransport } from "./transport";

describe("seed catalog",()=>{it("meets deliberate-practice content floors",()=>{expect(mentalMathExercises.length).toBeGreaterThanOrEqual(30);expect(quantSetupExercises.length).toBeGreaterThanOrEqual(15);expect(structureExercises.length).toBeGreaterThanOrEqual(15);expect(exhibitExercises.length).toBeGreaterThanOrEqual(10);expect(brainstormExercises.length).toBeGreaterThanOrEqual(10);expect(synthesisExercises.length).toBeGreaterThanOrEqual(10);expect(new Set(exerciseCatalog.map(x=>x.id)).size).toBe(exerciseCatalog.length)});it("fades guidance as variants become harder",()=>{expect(mentalMathExercises[0].guidance).toBeGreaterThan(mentalMathExercises[4].guidance);expect(mentalMathExercises[0].difficulty).toBeLessThan(mentalMathExercises[4].difficulty)})});
describe("pedagogical catalog",()=>{it("covers active modeling, completion, transfer, integration, retention, and assessment roles",()=>{const roles=new Set(exerciseCatalog.map(x=>x.learningFunction));for(const role of ["WORKED_EXAMPLE","PREDICTION_EXAMPLE","COMPLETION_PROBLEM","INDEPENDENT_PRACTICE","FAR_TRANSFER","INTEGRATED_CASE_SEGMENT","RETENTION_REVIEW","ASSESSMENT"])expect(roles).toContain(role)});it("has finite duration and transfer metadata",()=>exerciseCatalog.forEach(x=>{expect(Number.isFinite(x.estimatedDuration)).toBe(true);expect(x.deepPrinciple).toBeTruthy();expect(x.noveltyGroup).toBeTruthy()}))});
describe("qualitative evaluation",()=>{const evaluation={skill:"structuring",score:3,confidence:.6,reasoning:"Relevant but missing prioritization",evidence:[{turnId:"t1",excerpt:"I would examine customers, competition, and economics."}],errorTags:["weak-prioritization"],improvement:"Name the highest-value branch and why.",source:"ai" as const};it("requires evidence and anchored scores",()=>{expect(qualitativeEvaluationSchema.parse(evaluation).score).toBe(3);expect(()=>qualitativeEvaluationSchema.parse({...evaluation,score:83})).toThrow()});it("selectively escalates consequential low-confidence judgments",()=>{expect(shouldSecondEvaluate(evaluation)).toBe(true);expect(reliabilityWeight("human","former-interviewer")).toBeGreaterThan(reliabilityWeight("human","peer"))})});
describe("interview transports",()=>{it("does not disclose unrevealed facts and respects unavailable information",async()=>{const spec=cases[0],runtime=startCase(spec),transport=new TextInterviewTransport();const hidden=await transport.reply({message:"What is the parcel volume?",runtime,safeContext:spec});expect(hidden.text).not.toContain("18,000");const unavailable=await transport.reply({message:"Can I have competitor forecasts?",runtime,safeContext:spec});expect(unavailable.text).toMatch(/unavailable/)});it("voice degrades explicitly to independent text transport",async()=>{const spec=cases[0],runtime=startCase(spec);const reply=await new VoiceInterviewTransport().reply({message:"What should I do?",runtime,safeContext:spec});expect(reply.degraded).toBe(true);expect(reply.text).toMatch(/continuing in text mode/)})});
