export type CaseLink={title:string;brief:string;skills:string[];estimatedMinutes:number};
export type ChapterLesson={chapterId:string;concept:string;workedExample:string;predictionPrompt:string;expertReveal:string;practiceSequence:string[];caseLink:CaseLink;gate:string};
const link=(chapterId:string,title:string,skills:string[],estimatedMinutes=8):CaseLink=>({title:`Case Link · ${title}`,brief:`Apply ${title.toLowerCase()} inside the ${chapterId==="case-fundamentals"?"annotated opening-to-recommendation mini-case":"next segment of a realistic client decision"}. Keep the client objective visible and explain what the result changes.`,skills,estimatedMinutes});
export const chapterLessons:ChapterLesson[]=[
 {chapterId:"case-fundamentals",concept:"A case is a decision under uncertainty. Follow the whole flow: clarify → structure → prioritize → analyze → calculate → interpret → synthesize → recommend.",workedExample:"A meal-kit client asks whether to enter offices. The expert defines success, structures demand/economics/capability, prioritizes demand, finds a 25% margin, updates the hypothesis, and recommends a two-city pilot with retention as the key risk.",predictionPrompt:"Before the expert analyzes demand, what should they clarify first—and why?",expertReveal:"Clarify the decision, success metric, horizon, and constraints. These determine which evidence is useful and prevent technically correct but irrelevant analysis.",practiceSequence:["Model the complete case flow","Complete missing expert steps","Solve foundational business math"],caseLink:link("case-fundamentals","the complete case flow",["problem definition","structure","quant","synthesis"],12),gate:"Explain the whole flow and complete an integrated mini-case with support."},
 ...[
  ["define","Translate the prompt into a client decision, success metric, time horizon, constraints, and missing information.","Define whether a launch should proceed within 18 months while reaching positive contribution margin.","Which phrase turns this topic into a decision?","‘Should the client launch’ makes the choice explicit; the horizon and success metric make it testable.",["Complete partial objectives","Rank clarifying questions","Define an unseen problem"],"problem definition",["problem definition","clarifying questions"]],
  ["structure","Decompose the decision from first principles. Tailor and prioritize; do not dump a memorized framework.","For a repairable device launch: adoption, economics, delivery capability, and competitive response. Start with adoption.","Why should adoption come before detailed operations?","If credible adoption is absent, operational optimization cannot make the launch attractive.",["Study a worked tree","Repair overlap","Build and prioritize independently"],"a case opening",["problem definition","structure","prioritization"]],
  ["quant","Separate setup, execution, and interpretation. Name the question, inputs, equation, units, sanity check, and implication.","Break-even = $600k ÷ $12/unit = 50k units; proceed only if credible demand exceeds 50k.","What must be stated before dividing the numbers?","Define break-even volume, select fixed cost and contribution per unit, and verify that dollars cancel to units.",["Arithmetic retrieval","Equation setup","Interpretation transfer"],"a quantitative decision",["objective recall","quant setup","arithmetic","interpretation"]],
  ["exhibits","Orient, isolate signal, calculate if useful, then explain how the pattern changes the decision.","SMB retention fell while enterprise held. Prioritize SMB churn rather than company-wide acquisition.","What would merely reading the values fail to establish?","It would not identify the segment-specific cause or explain which investigation should come next.",["Simple orientation","Distractor removal","Multi-exhibit synthesis"],"an exhibit-led update",["exhibit interpretation","hypothesis","synthesis"]],
  ["judgment","Generate tailored categories, make assumptions explicit, and prioritize by impact and feasibility.","For museum evenings: demand, experience, partnerships, and operations; prioritize a limited pilot.","Why is a pilot stronger than a generic marketing list?","It tests the highest-uncertainty assumptions while limiting irreversible cost.",["Structured breadth","Specific ideas","Prioritized option"],"a client brainstorm",["structured creativity","business judgment","prioritization"]],
  ["synthesis","Use finding → implication → updated hypothesis → next step.","Demand exceeds capacity; service will deteriorate. A night shift remains viable, so test incremental economics.","Which sentence updates the working hypothesis?","‘A night shift remains viable’ states what the evidence now suggests before naming the next test.",["One finding","Multiple findings","Interim synthesis"],"an interim synthesis",["analysis","hypothesis update","next step"]],
  ["recommendations","Lead with the recommendation, evidence, risk, and practical next step.","Pilot the shift: it closes capacity and adds $2.16m. Adoption is the key risk; validate in two markets.","Why does the risk belong before the next step?","The risk explains what the next step must test, making the action decision-relevant.",["30-second close","60-second close","90-second verbal close"],"a recommendation",["synthesis","recommendation","concise communication"]]
 ].map(row=>{const [chapterId,concept,workedExample,predictionPrompt,expertReveal,practiceSequence,title,skills]=row;return {chapterId:String(chapterId),concept:String(concept),workedExample:String(workedExample),predictionPrompt:String(predictionPrompt),expertReveal:String(expertReveal),practiceSequence:practiceSequence as string[],caseLink:link(String(chapterId),String(title),skills as string[]),gate:"Requires independent evidence in two contexts, transfer, delayed retrieval, and integrated case execution."} as ChapterLesson}),
 ...["two-skill","segments","mini","full","unfamiliar","pressure","firm","readiness"].map((chapterId,index):ChapterLesson=>({chapterId,concept:["Systematically combine skills while preserving the client decision.","Sustain reasoning through a realistic segment without instructional interruption.","Integrate most skills under moderate complexity.","Lead a complete predetermined case.","Transfer without an announced archetype.","Maintain quality under credible ambiguity and pressure.","Apply competence to an editable firm format.","Demonstrate consistent unseen, unassisted performance."][index],workedExample:"Trace the evidence, repair the weakest transition, then solve an analogous segment.",predictionPrompt:"Which transition between skills is most likely to fail here?",expertReveal:"Prioritize the transition with the greatest effect on the client decision, not the easiest isolated drill.",practiceSequence:["Guided integration","Independent attempt","Unseen transfer"],caseLink:link(chapterId,"integrated case reasoning",["case leadership","synthesis","recommendation"],15),gate:"Requires independent, transferred, retained, and integrated evidence."}))
];
