import { z } from "zod";

export const skillIds = ["problem-definition","clarifying-questions","structuring","prioritization","hypothesis","quant-setup","arithmetic-accuracy","arithmetic-speed","market-sizing","exhibit-interpretation","data-extraction","quant-interpretation","brainstorming","business-judgment","synthesis","recommendation","case-leadership","concise-communication","signposting","interviewer-cues","story-selection","specificity","personal-ownership","leadership","influence","conflict","failure-learning","teamwork","consulting-motivation","firm-motivation","storytelling","follow-up-depth","behavioral-concision"] as const;
export type SkillId = typeof skillIds[number];
export type EvidenceSource = "deterministic" | "ai" | "human";
export type SkillState = { id: SkillId; label: string; mastery: number; uncertainty: number; observations: number; trend: "up"|"flat"|"down"; errors: string[]; lastPractice?: string; nextReview?: string; drill: number; case: number; byDifficulty: Record<string,number>; sources: EvidenceSource[] };
export type Attempt = { id:string; exerciseId:string; skill:SkillId; answer:string; correct:boolean; score:number; at:string; attemptNo:number; errorTag?:string; guidanceLevel?:0|1|2|3|4; hintsUsed?:number; independent?:boolean; transferDistance?:0|1|2|3; integrated?:boolean; delayed?:boolean; context?:string; confidence?:"LOW"|"MEDIUM"|"HIGH"; learningFunction?:string };

export const chapters = [
  ["case-fundamentals","Case fundamentals","Foundations"],["define","Define the problem","Foundations"],["structure","Structuring","Problem Solver"],["quant","Quantitative reasoning","Quantitative Analyst"],["exhibits","Exhibits","Insight Builder"],["judgment","Business judgment","Insight Builder"],["synthesis","Synthesis","Case Integrator"],["recommendations","Recommendations","Case Integrator"],["two-skill","Two-skill challenges","Case Integrator"],["segments","Case segments","Full Case Ready"],["mini","Mini cases","Full Case Ready"],["full","Full cases","Full Case Ready"],["unfamiliar","Unfamiliar cases","Interview Ready"],["pressure","Pressure cases","Interview Ready"],["firm","Firm simulation","Interview Ready"],["readiness","Interview readiness","Interview Ready"]
] as const;

const infoSchema = z.object({ id:z.string(), text:z.string(), stage:z.string() });
const calcSchema = z.object({ id:z.string(), prompt:z.string(), answer:z.number(), tolerance:z.number().nonnegative(), unit:z.string() });
export const caseSpecSchema = z.object({
 id:z.string(), version:z.string(), title:z.string(), industry:z.string(), businessModel:z.string(), problemFamily:z.string(), poolRole:z.enum(["TRAINING","TRANSFER","READINESS_HOLDOUT"]).default("TRAINING"), holdoutEligible:z.boolean().default(false), difficulty:z.number().int().min(1).max(5), style:z.enum(["interviewer-led","candidate-led","hybrid"]), targetMinutes:z.number().positive(), context:z.string(), objective:z.string(), constraints:z.array(z.string()), clientFacts:z.array(infoSchema), hiddenFacts:z.array(infoSchema), irrelevantFacts:z.array(infoSchema), unavailable:z.array(z.string()), calculations:z.array(calcSchema), exhibits:z.array(z.object({id:z.string(),title:z.string(),releaseStage:z.string(),columns:z.array(z.string()),rows:z.array(z.array(z.union([z.string(),z.number()]))) })), stages:z.array(z.object({id:z.string(),objective:z.string(),requiredInsights:z.array(z.string()),next:z.array(z.string())})), conclusions:z.array(z.string()), unsupported:z.array(z.string()), risks:z.array(z.string()), nextSteps:z.array(z.string())
}).superRefine((c,ctx)=>{ const ids=new Set(c.stages.map(s=>s.id)); for(const s of c.stages) for(const n of s.next) if(!ids.has(n)) ctx.addIssue({code:"custom",message:`Unreachable transition ${n}`}); for(const x of [...c.clientFacts,...c.hiddenFacts]) if(!ids.has(x.stage)) ctx.addIssue({code:"custom",message:`Unknown fact stage ${x.stage}`}); });
export type CaseSpec = z.infer<typeof caseSpecSchema>;
export type Runtime = { specId:string; specVersion:string; stage:string; revealed:string[]; availableExhibits:string[]; hints:number; completedInsights:string[]; turns:{role:"interviewer"|"candidate";text:string}[]; complete:boolean };

export function validateAndFreezeCase(input:unknown):Readonly<CaseSpec>{ const parsed=caseSpecSchema.parse(input); if(new Set(parsed.calculations.map(x=>x.id)).size!==parsed.calculations.length) throw new Error("Duplicate calculation id"); return deepFreeze(parsed); }
function deepFreeze<T>(x:T):Readonly<T>{ if(x&&typeof x==="object"){ Object.freeze(x); Object.values(x as object).forEach(deepFreeze); } return x; }
export function startCase(spec:CaseSpec):Runtime { const first=spec.stages[0]; return {specId:spec.id,specVersion:spec.version,stage:first.id,revealed:spec.clientFacts.filter(f=>f.stage===first.id).map(f=>f.id),availableExhibits:spec.exhibits.filter(e=>e.releaseStage===first.id).map(e=>e.id),hints:0,completedInsights:[],turns:[{role:"interviewer",text:`${spec.context} ${spec.objective}`}],complete:false}; }
export function advanceCase(spec:CaseSpec,r:Runtime,insight?:string):Runtime { const current=spec.stages.find(s=>s.id===r.stage)!; const completed=insight?[...new Set([...r.completedInsights,insight])]:r.completedInsights; if(!current.requiredInsights.every(i=>completed.includes(i))) return {...r,completedInsights:completed}; const next=current.next[0]; if(!next) return {...r,completedInsights:completed,complete:true}; return {...r,stage:next,completedInsights:completed,revealed:[...r.revealed,...spec.clientFacts.filter(f=>f.stage===next).map(f=>f.id)],availableExhibits:[...r.availableExhibits,...spec.exhibits.filter(e=>e.releaseStage===next).map(e=>e.id)]}; }
export function gradeNumber(answer:number|string,expected:number,tolerance:number){
 const raw=String(answer).replace(/[$,%\s]/g,""),value=Number(raw),error=Math.abs(value-expected),explicitPrecision=typeof answer==="string",decimals=(raw.split(".")[1]??"").length,roundingMatch=explicitPrecision&&Number.isFinite(value)&&value===Number(expected.toFixed(decimals)),correct=Number.isFinite(value)&&(error<=tolerance||roundingMatch);
 return {correct,error,score:correct?5:error<=Math.max(tolerance*3,Math.abs(expected)*.1)?3:1,value,roundingMatch,decimals};
}
export function nextReview(correct:boolean, priorInterval=1, now=new Date()){ const days=correct?Math.min(30,Math.max(2,Math.round(priorInterval*2.2))):1; const date=new Date(now); date.setUTCDate(date.getUTCDate()+days); return {intervalDays:days,nextReview:date.toISOString().slice(0,10)}; }
export function masteryGate(s:SkillState[]){ const enough=s.every(x=>x.observations>=3); const independent=s.every(x=>x.mastery>=.68&&x.uncertainty<=.28); return {passed:enough&&independent,reason:!enough?"More independent evidence needed":!independent?"One or more skills need reinforcement":"Consistent independent performance"}; }
export function trainingPriority(s:SkillState,today:string){ const weakness=1-s.mastery, due=!s.nextReview||s.nextReview<=today?1.5:.8, gap=Math.max(.15,s.drill-s.case+1); return weakness*(1+s.uncertainty)*due*gap; }
export function makePlan(skills:SkillState[],minutes:number,today:string){ const ranked=[...skills].sort((a,b)=>trainingPriority(b,today)-trainingPriority(a,today)); const slots=minutes<=15?2:minutes<=30?3:minutes<=60?4:5; return ranked.slice(0,slots).map((s,i)=>({skill:s.id,title:i===0?`Repair: ${s.label}`:`Practice: ${s.label}`,minutes:Math.max(5,Math.floor(minutes/slots)),why:s.nextReview&&s.nextReview<=today?"A prior reasoning error is due for retrieval.":i===0?"Highest combined weakness, uncertainty, and transfer gap.":"Interleaves a related skill to strengthen transfer."})); }
export function applyAttemptEvidence(skills:SkillState[],attempt:Attempt):SkillState[]{
 return skills.map(skill=>{if(skill.id!==attempt.skill)return skill;const observed=(attempt.score-1)/4,weight=attempt.attemptNo>1?.12:.2;
  const mastery=Math.max(0,Math.min(1,skill.mastery*(1-weight)+observed*weight)),review=nextReview(attempt.correct,attempt.correct?3:1,new Date(attempt.at));
  return {...skill,mastery,uncertainty:Math.max(.08,skill.uncertainty*(attempt.correct?.88:1.04)),observations:skill.observations+1,trend:mastery>skill.mastery+.015?"up":mastery<skill.mastery-.015?"down":"flat",
   errors:attempt.errorTag?[...new Set([attempt.errorTag,...skill.errors])]:skill.errors,lastPractice:attempt.at.slice(0,10),nextReview:review.nextReview,drill:skill.drill*.75+observed*.25,sources:[...new Set([...skill.sources,"deterministic" as const])]};});
}
