import { z } from "zod";
import { applyAttemptEvidence, Attempt, chapters, SkillState } from "./domain";
import { seedSkills } from "./seed";
import type { CaseMode } from "./case-engine";
import type { SimulationEvidence } from "./readiness";
import type {StoryActivityRecord} from "./story";
import {learningProfile,scheduleReview, type ReviewItem, type RootErrorTag, type SkillEvidence} from "./pedagogy";

export const STORE_KEY="casecraft-learner-v6",STORE_VERSION=6;
export type BehavioralStory={id:string;title:string;tags:string[];context:string;objective:string;actions:string;reasoning:string;obstacles:string;dynamics:string;result:string;learning:string;alternatives:string[];updatedAt:string};
export type HumanPractice={id:string;partner:string;date:string;caseName:string;style:string;evaluatorType:string;skillRatings:Record<string,number>;feedback:string;errors:string[];strengths:string[]};
export type CaseHistory=SimulationEvidence&{id:string;title:string;mode:CaseMode;calculationAccuracy:number|null;insightCoverage:number;caseVersion:string};
export type DiagnosticAnswer={experience:"new"|"some"|"experienced";mathComfort:1|2|3|4|5;structureComfort:1|2|3|4|5;interviewDate?:string};
export type LearnerState={version:6;name:string;onboarded:boolean;minutes:number;targetFirm:string;interviewDate:string;skills:SkillState[];attempts:Attempt[];evidence:SkillEvidence[];reviews:ReviewItem[];seenCaseIds:string[];caseHistory:CaseHistory[];stories:BehavioralStory[];humanLogs:HumanPractice[];completedChapterIds:string[];diagnosticComplete:boolean;storyRecords:StoryActivityRecord[];diagnostic?:DiagnosticAnswer};
const stateSchema=z.object({version:z.literal(6),name:z.string(),onboarded:z.boolean(),minutes:z.number().int().min(15).max(90),targetFirm:z.string(),interviewDate:z.string(),skills:z.array(z.any()),attempts:z.array(z.any()),evidence:z.array(z.any()),reviews:z.array(z.any()),seenCaseIds:z.array(z.string()),caseHistory:z.array(z.any()),stories:z.array(z.any()),humanLogs:z.array(z.any()),completedChapterIds:z.array(z.string()),diagnosticComplete:z.boolean(),storyRecords:z.array(z.any()),diagnostic:z.any().optional()});
const emptySkills=():SkillState[]=>structuredClone(seedSkills).map(skill=>({...skill,mastery:0,uncertainty:1,observations:0,trend:"flat" as const,errors:[],lastPractice:undefined,nextReview:undefined,drill:0,case:0,byDifficulty:{},sources:[]}));
export function initialLearner():LearnerState{return {version:6,name:"",onboarded:false,minutes:30,targetFirm:"",interviewDate:"",skills:emptySkills(),attempts:[],evidence:[],reviews:[],seenCaseIds:[],caseHistory:[],stories:[],humanLogs:[],completedChapterIds:[],diagnosticComplete:false,storyRecords:[]}}
function rebuildObservedProgress(state:LearnerState){let skills=emptySkills();for(const attempt of state.attempts)skills=applyAttemptEvidence(skills,attempt);for(const item of state.caseHistory){const integrated=new Set(["case-leadership","synthesis","recommendation","concise-communication","quant-interpretation"]),score=item.criticalSkillScore;skills=skills.map(s=>integrated.has(s.id)?{...s,case:s.case*.7+score*.3,mastery:s.mastery*.88+score*.12,observations:s.observations+1,uncertainty:Math.max(.08,s.uncertainty*.9),lastPractice:item.completedAt.slice(0,10)}:s)}return {...state,skills}}
export function loadLearner(raw:string|null):{state:LearnerState;warning?:string}{if(!raw)return {state:initialLearner()};try{const parsed=JSON.parse(raw);const legacy=parsed.version!==STORE_VERSION,migrated={...initialLearner(),...parsed,version:STORE_VERSION,minutes:[15,30,45,60,90].includes(Number(parsed.minutes))?Number(parsed.minutes):30,evidence:parsed.evidence??[],reviews:parsed.reviews??[],seenCaseIds:parsed.seenCaseIds??[],caseHistory:parsed.caseHistory??[],diagnosticComplete:parsed.diagnosticComplete??false,storyRecords:parsed.storyRecords??[],completedChapterIds:legacy?[]:(parsed.completedChapterIds??[]),targetFirm:parsed.targetFirm??"",interviewDate:parsed.interviewDate??"",humanLogs:(parsed.humanLogs??[]).map((x:Record<string,unknown>)=>({id:crypto.randomUUID(),date:new Date().toISOString().slice(0,10),caseName:"External practice",style:"hybrid",skillRatings:{},errors:[],strengths:[],...x}))};return {state:rebuildObservedProgress(stateSchema.parse(migrated) as LearnerState),...(legacy?{warning:"Your learner profile was upgraded. Progress was rebuilt only from real attempts and completed cases."}:{})}}catch{return {state:initialLearner(),warning:"Saved data was invalid, so a fresh local profile was loaded."}}}
export function applyDiagnostic(state:LearnerState,name:string,minutes:number,d:DiagnosticAnswer):LearnerState{
 const safeMinutes=[15,30,45,60,90].includes(minutes)?minutes:30;
 return {...state,name:name.trim()||"Candidate",minutes:safeMinutes,onboarded:true,interviewDate:d.interviewDate??"",diagnostic:d,skills:emptySkills()};
}
export function recordAttempt(state:LearnerState,attempt:Attempt):LearnerState{const normalized=Math.max(0,Math.min(1,(attempt.score-1)/4)),tag=(attempt.errorTag?.toUpperCase().replaceAll("-","_")??undefined) as RootErrorTag|undefined;const evidence:SkillEvidence={id:crypto.randomUUID(),skillId:attempt.skill,attemptId:attempt.id,evidenceType:attempt.integrated?"INTEGRATION":attempt.delayed?"RETENTION":(attempt.transferDistance??0)>0?"TRANSFER":attempt.independent?"INDEPENDENT":"ACQUISITION",context:attempt.context??"skill lab",difficulty:1,independent:attempt.independent??(attempt.guidanceLevel??1)<=1,transferDistance:attempt.transferDistance??0,delayed:attempt.delayed??false,integrated:attempt.integrated??false,score:normalized,confidence:attempt.confidence,guidanceLevel:attempt.guidanceLevel??1,hintsUsed:attempt.hintsUsed??0,errorTag:tag,timestamp:attempt.at};const reviews=!attempt.correct&&tag?[...state.reviews,scheduleReview({id:crypto.randomUUID(),skillId:attempt.skill,underlyingErrorPattern:tag,sourceAttemptId:attempt.id,transferContext:"same principle in a different industry"},new Date(attempt.at))]:state.reviews;return {...state,attempts:[...state.attempts,attempt],evidence:[...state.evidence,evidence],reviews,skills:applyAttemptEvidence(state.skills,attempt)}}
export function recordCase(state:LearnerState,item:CaseHistory):LearnerState{
 const score=item.criticalSkillScore;
 const integrated=new Set(["case-leadership","synthesis","recommendation","concise-communication","quant-interpretation"]);
 const skills=state.skills.map(s=>integrated.has(s.id)?{...s,case:s.case*.7+score*.3,mastery:s.mastery*.88+score*.12,observations:s.observations+1,uncertainty:Math.max(.08,s.uncertainty*.9),lastPractice:item.completedAt.slice(0,10)}:s);
 return {...state,caseHistory:[...state.caseHistory,item],seenCaseIds:[...new Set([...state.seenCaseIds,item.caseId])],skills};
}
export function chapterProgress(state:LearnerState){return chapters.map((chapter,index)=>{const relevant=index<3?["problem-definition","clarifying-questions","structuring"]:index<5?["quant-setup","arithmetic-accuracy","exhibit-interpretation"]:index<8?["business-judgment","synthesis","recommendation"]:["case-leadership","concise-communication"];const skills=state.skills.filter(s=>relevant.includes(s.id)),profiles=skills.map(s=>learningProfile(s.id,state.evidence));const mastery=skills.length?skills.reduce((a,s)=>a+s.mastery,0)/skills.length:0,passed=profiles.length>0&&profiles.every(p=>p.stage==="MASTERED");return {id:chapter[0],mastery,passed,manual:state.completedChapterIds.includes(chapter[0])}})}
export function exportLearner(state:LearnerState){return JSON.stringify({...state,exportedAt:new Date().toISOString()},null,2)}
