import { CaseSpec, SkillState, skillIds, validateAndFreezeCase } from "./domain";
const labels:Record<string,string>={"problem-definition":"Problem definition","clarifying-questions":"Clarifying questions",structuring:"Structuring",prioritization:"Prioritization",hypothesis:"Hypothesis formation","quant-setup":"Quantitative setup","arithmetic-accuracy":"Arithmetic accuracy","arithmetic-speed":"Arithmetic speed","market-sizing":"Market sizing","exhibit-interpretation":"Exhibit interpretation","data-extraction":"Relevant data","quant-interpretation":"Quantitative interpretation",brainstorming:"Structured creativity","business-judgment":"Business judgment",synthesis:"Interim synthesis",recommendation:"Final recommendation","case-leadership":"Case leadership","concise-communication":"Concise communication",signposting:"Signposting","interviewer-cues":"Interviewer cues","story-selection":"Story selection",specificity:"Specificity","personal-ownership":"Personal ownership",leadership:"Leadership",influence:"Influence",conflict:"Conflict","failure-learning":"Failure & learning",teamwork:"Teamwork","consulting-motivation":"Why consulting","firm-motivation":"Why this firm",storytelling:"Story structure","follow-up-depth":"Follow-up depth","behavioral-concision":"Behavioral concision"};
export const seedSkills:SkillState[]=skillIds.map((id,i)=>({id,label:labels[id],mastery:i%7===0?.42:i%5===0?.58:.7,uncertainty:i%4===0?.34:.2,observations:i%6===0?2:5,trend:i%7===0?"down":i%3===0?"up":"flat",errors:i%7===0?["implication-missing"]:[],lastPractice:"2026-09-10",nextReview:i%7===0?"2026-09-12":"2026-09-18",drill:.72,case:i%7===0?.4:.65,byDifficulty:{guided:.78,independent:.61},sources:["deterministic"]}));
const base={version:"1.0.0",difficulty:3,style:"hybrid" as const,targetMinutes:35,constraints:["Decision required in six weeks"],irrelevantFacts:[],unavailable:["Competitor internal forecasts"],stages:[{id:"open",objective:"Clarify the decision and structure the problem",requiredInsights:["objective"],next:["analysis"]},{id:"analysis",objective:"Evaluate the economics",requiredInsights:["economics"],next:["recommend"]},{id:"recommend",objective:"Make an evidence-backed recommendation",requiredInsights:["recommendation"],next:[]}],unsupported:["Assume demand without evidence"],risks:["Adoption may be slower than forecast"],nextSteps:["Pilot in two representative markets"]};
const specs:CaseSpec[]=[
 { ...base,id:"northline",title:"The night-shift decision",industry:"Logistics",businessModel:"Urban parcel network",problemFamily:"Ambiguous strategic decision",context:"Northline runs a city parcel network and is considering a night sorting shift.",objective:"Determine whether the client should add the shift next quarter.",clientFacts:[{id:"volume",stage:"analysis",text:"Current volume is 18,000 parcels per day."}],hiddenFacts:[{id:"margin",stage:"analysis",text:"Incremental contribution is $1.80 per parcel."}],calculations:[{id:"annual",prompt:"Annual contribution from 4,000 additional parcels per day over 300 days",answer:2160000,tolerance:1000,unit:"USD"}],exhibits:[{id:"capacity",title:"Daily network demand and capacity",releaseStage:"analysis",columns:["Period","Demand","Capacity"],rows:[["Current",18000,19000],["Forecast",23000,19000],["With shift",23000,25000]]}],conclusions:["Pilot the night shift because forecast demand exceeds current capacity and economics are positive."]},
 { ...base,id:"luma",title:"A museum after hours",industry:"Nonprofit",businessModel:"Membership and admissions",problemFamily:"Growth",context:"Luma Museum wants to expand access without weakening its finances.",objective:"Assess a paid Friday evening program.",clientFacts:[{id:"attendance",stage:"analysis",text:"Expected attendance is 600 visitors each Friday."}],hiddenFacts:[{id:"cost",stage:"analysis",text:"Staffing and utilities cost $7,500 per evening."}],calculations:[{id:"breakeven",prompt:"Ticket price to cover $7,500 with 600 visitors",answer:12.5,tolerance:.05,unit:"USD/visitor"}],exhibits:[],conclusions:["Test the program at a ticket price above $12.50 with access safeguards."]},
 { ...base,id:"aerleaf",title:"Cold chain at altitude",industry:"Healthcare logistics",businessModel:"Drone delivery",problemFamily:"Market entry",context:"Aerleaf is evaluating rural diagnostic-sample delivery.",objective:"Decide whether to enter one regional market.",clientFacts:[{id:"routes",stage:"analysis",text:"The region has 40 eligible clinic routes."}],hiddenFacts:[{id:"profit",stage:"analysis",text:"Each mature route contributes $28,000 annually."}],calculations:[{id:"profit",prompt:"Annual contribution for 40 routes at $28,000",answer:1120000,tolerance:1000,unit:"USD"}],exhibits:[],conclusions:["Enter through a staged route pilot, contingent on regulatory approval."]}
];
export const cases=specs.map(validateAndFreezeCase);
export const drills=[
 {id:"margin",skill:"arithmetic-accuracy" as const,prompt:"Revenue is $48m and costs are $36m. What is the operating margin?",setup:"(Revenue − costs) ÷ revenue",answer:25,unit:"%",tolerance:.1,implication:"A 25% margin leaves meaningful room to fund growth."},
 {id:"setup",skill:"quant-setup" as const,prompt:"A retailer asks whether a new store breaks even. Write the equation before calculating.",setup:"Break-even volume = fixed costs ÷ contribution per unit",answer:50000,unit:"units",tolerance:1,implication:"Compare expected volume with 50,000 units to decide whether to proceed."},
 {id:"growth",skill:"quant-interpretation" as const,prompt:"Customers grew from 80k to 100k. Calculate growth, then state why it matters.",setup:"(New − old) ÷ old",answer:25,unit:"%",tolerance:.1,implication:"25% growth supports demand, but profitability and retention still need testing."}
];
export const behavioralQuestions=["Tell me about a time you influenced a skeptical stakeholder.","Describe a failure that changed how you lead.","Tell me about a conflict within a team.","Why consulting, and why now?"];
