import type {Attempt,SkillId} from "./domain";
import type {ExerciseLearningFunction,RootErrorTag,SkillEvidence} from "./pedagogy";

export type StoryActivityKind="CONTENT"|"EXERCISE"|"CASE_LINK"|"GATE"|"RETENTION";
export type StoryActivitySpec={id:string;chapterId:string;title:string;kind:StoryActivityKind;learningFunction:ExerciseLearningFunction;skills:SkillId[];prerequisites:string[];exerciseId?:string;guidance:0|1|2|3|4;difficulty:1|2|3|4|5;transferDistance:0|1|2|3;minutes:number;evidenceType?:SkillEvidence["evidenceType"];gateContribution:boolean;prompt?:string;expertMove?:string;why:string};
export type StoryActivityRecord={activityId:string;chapterId:string;status:"COMPLETED"|"REMEDIATION_REQUIRED";score:number;attemptId?:string;errorTag?:RootErrorTag;completedAt:string};
export type StoryChapterPlan={id:string;title:string;objective:string;caseRole:string;activities:StoryActivitySpec[];gate:{independent:number;transfer:number;integration:number;minimumScore:number;retention:number}};
export type StoryChapterStatus="AVAILABLE"|"INTRODUCED"|"PRACTICING"|"REMEDIATION"|"INDEPENDENT"|"TRANSFER"|"INTEGRATION"|"RETENTION_PENDING"|"GATE_READY"|"PASSED"|"MANUALLY_BYPASSED";
const A=(chapterId:string,id:string,title:string,learningFunction:ExerciseLearningFunction,kind:StoryActivityKind,minutes:number,extra:Partial<StoryActivitySpec>={}):StoryActivitySpec=>({id:`${chapterId}:${id}`,chapterId,title,learningFunction,kind,minutes,skills:["problem-definition"],prerequisites:[],guidance:kind==="CONTENT"?4:2,difficulty:1,transferDistance:0,gateContribution:false,why:"This is the next required step in the authored chapter path.",...extra});
const chain=(items:StoryActivitySpec[])=>items.map((item,index)=>({...item,prerequisites:index?[items[index-1].id]:[]}));

const chapter0=chain([
 A("case-fundamentals","brief","Receive the client prompt","WORKED_EXAMPLE","CONTENT",1,{prompt:"FreshBite, a meal-kit company, is considering weekday lunch delivery to offices. Should it launch a two-city pilot?",expertMove:"An experienced candidate first converts the topic into a decision: should FreshBite pilot office lunches, under what economic and customer conditions?",why:"Start with the whole task so every later skill has a place."}),
 A("case-fundamentals","decision","Define the client decision","PREDICTION_EXAMPLE","CONTENT",2,{prompt:"What decision must the client make, and what would success mean?",expertMove:"Decision: whether to launch a two-city pilot. Success: attractive contribution economics and credible repeat demand within the pilot horizon."}),
 A("case-fundamentals","clarify","Choose useful clarification","DISCRIMINATION","CONTENT",2,{prompt:"Which matters first: the CEO's favorite menu, or whether the goal is revenue growth or profitable growth? Explain.",expertMove:"The growth objective changes the required analysis; menu preference does not yet change the decision."}),
 A("case-fundamentals","structure","Build the analysis map","COMPLETION_PROBLEM","CONTENT",2,{prompt:"Complete the structure: demand, economics, delivery capability, and _____. Which branch comes first?",expertMove:"Add customer retention or competitive response. either can be valid if justified. Start with demand because weak adoption makes detailed operations irrelevant.",skills:["structuring","prioritization"]}),
 A("case-fundamentals","quant","Calculate pilot contribution","GUIDED_PRACTICE","EXERCISE",4,{exerciseId:"math-margin-1",skills:["arithmetic-accuracy","quant-interpretation"],evidenceType:"ACQUISITION",guidance:3}),
 A("case-fundamentals","exhibit","Interpret the demand signal","PREDICTION_EXAMPLE","CONTENT",2,{prompt:"Trial is high, but week-four repeat purchase is only 18%. What does that imply for the launch decision?",expertMove:"Initial interest exists, but retention threatens lifetime economics. Test repeat demand before scaling.",skills:["exhibit-interpretation","quant-interpretation"]}),
 A("case-fundamentals","synthesis","Update the hypothesis","GUIDED_PRACTICE","CONTENT",2,{prompt:"State the finding, implication, updated hypothesis, and next step.",expertMove:"Finding: trial is strong but repeat is 18%. Implication: demand may not sustain attractive economics. Hypothesis: launch is premature. Next: test retention drivers in a limited pilot.",skills:["synthesis"]}),
 A("case-fundamentals","recommend","Recommend a decision","INTEGRATED_CASE_SEGMENT","CASE_LINK",3,{prompt:"Give a recommendation with evidence, risk, and next step.",expertMove:"Run a limited pilot rather than a full launch; early demand is promising, but 18% repeat creates economic risk. Test retention in two offices before scaling.",skills:["recommendation","synthesis","concise-communication"],evidenceType:"INTEGRATION",guidance:2,transferDistance:1,gateContribution:true}),
 A("case-fundamentals","gate","Explain the complete case flow","ASSESSMENT","GATE",3,{prompt:"Without looking back, explain the case flow and why each step matters.",expertMove:"A strong answer connects clarify, structure, prioritize, analyze, calculate, interpret, synthesize, and recommend to the client decision.",skills:["case-leadership"],evidenceType:"INDEPENDENT",guidance:1,gateContribution:true})
]);
const authored:{id:string;title:string;objective:string;role:string;skill:SkillId;exercise:string;casePrompt:string}[]=[
 {id:"define",title:"Define the problem",objective:"Turn an ambiguous prompt into a precise decision, metric, horizon, constraints, and useful questions.",role:"A strong opening prevents irrelevant analysis.",skill:"problem-definition",exercise:"setup-1",casePrompt:"A clinic asks how to grow. Clarify the decision, metric, horizon, constraints, and two questions that would change your analysis."},
 {id:"structure",title:"Structuring",objective:"Build tailored, decision-led structures and prioritize where analysis should begin.",role:"A structure is a plan for solving the client decision—not a memorized list.",skill:"structuring",exercise:"structure-1",casePrompt:"A repairable-device company is considering launch. Build and prioritize a structure after stating the objective."},
 {id:"quant",title:"Quantitative reasoning",objective:"Separate setup, execution, units, sanity checking, and business implication.",role:"Correct arithmetic is useful only when it answers the right client question.",skill:"quant-setup",exercise:"setup-2",casePrompt:"A parcel operator faces a capacity decision. State the question, relevant inputs, equation, units, calculation logic, and implication."},
 {id:"exhibits",title:"Exhibits",objective:"Orient, observe, analyze, interpret, and connect evidence to the decision.",role:"Interviewers reward implications, not reading chart labels aloud.",skill:"exhibit-interpretation",exercise:"exhibit-1",casePrompt:"Retention falls only in the small-business segment while enterprise is stable. State the pattern, implication, hypothesis update, and next analysis."},
 {id:"judgment",title:"Business judgment",objective:"Generate structured, specific, commercially realistic options and prioritize one.",role:"Good brainstorming creates choices the client can act on.",skill:"business-judgment",exercise:"brainstorm-1",casePrompt:"A museum is considering evening hours. Generate categories and specific options, then prioritize one with assumptions and tradeoffs."},
 {id:"synthesis",title:"Synthesis",objective:"Convert findings into implications, an updated hypothesis, and a next step.",role:"Synthesis keeps the case moving rather than merely summarizing history.",skill:"synthesis",exercise:"synthesis-1",casePrompt:"Demand exceeds current capacity, but a night shift appears economic. Give a mid-case synthesis and name the next test."},
 {id:"recommendations",title:"Recommendations",objective:"Deliver a supported recommendation with evidence, risk, and practical next step.",role:"The close must answer the client decision without overstating the evidence.",skill:"recommendation",exercise:"synthesis-2",casePrompt:"Close a pilot decision using the available demand and economic evidence; include a caveat and next step."}
];
function skillPlan(x:typeof authored[number]):StoryChapterPlan{const activities=chain([
 A(x.id,"orient",`Why ${x.title.toLowerCase()} matters`,"WORKED_EXAMPLE","CONTENT",2,{prompt:x.role,expertMove:x.objective,skills:[x.skill]}),
 A(x.id,"discriminate","Distinguish strong from superficial reasoning","DISCRIMINATION","CONTENT",3,{prompt:`Compare a decision-relevant ${x.title.toLowerCase()} response with one that sounds polished but does not change the analysis. What makes the stronger response useful?`,expertMove:"The stronger response connects directly to the objective, identifies what matters, and creates a justified analytical next step.",skills:[x.skill]}),
 A(x.id,"complete","Complete a strong response","COMPLETION_PROBLEM","EXERCISE",6,{exerciseId:x.exercise,skills:[x.skill],evidenceType:"ACQUISITION",guidance:2}),
 A(x.id,"independent","Solve independently","INDEPENDENT_PRACTICE","EXERCISE",8,{exerciseId:x.exercise.replace(/\d+$/,m=>String(Math.min(9,Number(m)+1))),skills:[x.skill],evidenceType:"INDEPENDENT",guidance:1,difficulty:2,gateContribution:true}),
 A(x.id,"transfer","Transfer to a different industry","FAR_TRANSFER","EXERCISE",8,{exerciseId:x.exercise.replace(/\d+$/,m=>String(Math.min(10,Number(m)+2))),skills:[x.skill],evidenceType:"TRANSFER",guidance:1,difficulty:3,transferDistance:3,gateContribution:true,why:"Independent performance is established; now preserve the reasoning while changing the surface context."}),
 A(x.id,"case-link",`Case Link · ${x.title}`,"INTEGRATED_CASE_SEGMENT","CASE_LINK",8,{prompt:x.casePrompt,expertMove:"A strong response uses the new skill while preserving the client objective and previously learned reasoning.",skills:[x.skill,"case-leadership"],evidenceType:"INTEGRATION",guidance:1,difficulty:3,transferDistance:2,gateContribution:true}),
 A(x.id,"gate",`${x.title} mastery check`,"ASSESSMENT","GATE",6,{prompt:`Apply ${x.title.toLowerCase()} to an unseen client situation and explain why your approach is decision-relevant.`,expertMove:"The gate requires an independent, tailored response with a justified priority and no unresolved major misconception.",skills:[x.skill],evidenceType:"INDEPENDENT",guidance:0,difficulty:4,transferDistance:3,gateContribution:true})
 ]);return {id:x.id,title:x.title,objective:x.objective,caseRole:x.role,activities,gate:{independent:2,transfer:1,integration:1,minimumScore:.65,retention:1}}}
const later=["two-skill","segments","mini","full","unfamiliar","pressure","firm","readiness"].map((id,index):StoryChapterPlan=>{const title=["Two-skill challenges","Case segments","Mini cases","Full cases","Unfamiliar cases","Pressure cases","Firm simulation","Interview readiness"][index];return {id,title,objective:"Sustain increasingly independent, integrated reasoning in realistic consulting situations.",caseRole:"Isolated exercises progressively give way to complete case performance.",activities:chain([A(id,"orient",`Prepare for ${title.toLowerCase()}`,"PREDICTION_EXAMPLE","CONTENT",2,{prompt:"Which transition between skills is most likely to fail, and how will you protect it?",expertMove:"Keep the objective visible, signpost transitions, and interpret every analysis before moving on.",skills:["case-leadership"]}),A(id,"practice",`Practice ${title.toLowerCase()}`,"INTEGRATED_CASE_SEGMENT","CASE_LINK",15,{prompt:"Complete the selected predetermined case segment without losing the client objective.",expertMove:"Debrief the highest-value reasoning transition, then retry it.",skills:["case-leadership","synthesis"],evidenceType:"INTEGRATION",guidance:index<2?1:0,difficulty:Math.min(5,3+Math.floor(index/2)) as 1|3|4|5,gateContribution:true}),A(id,"gate",`${title} check`,"ASSESSMENT","GATE",15,{prompt:"Complete an unseen integrated assessment.",expertMove:"Progress requires independent, supported reasoning—not completion count.",skills:["case-leadership"],evidenceType:"INDEPENDENT",guidance:0,difficulty:5,transferDistance:3,gateContribution:true})]),gate:{independent:1,transfer:0,integration:1,minimumScore:.7,retention:index<3?0:1}}});
export const storyChapterPlans:StoryChapterPlan[]=[{id:"case-fundamentals",title:"Case fundamentals",objective:"Build a mental model of the complete consulting case before isolating component skills.",caseRole:"See how every skill contributes to one client decision.",activities:chapter0,gate:{independent:1,transfer:0,integration:1,minimumScore:.6,retention:0}},...authored.map(skillPlan),...later];
export function chapterEvidence(plan:StoryChapterPlan,records:StoryActivityRecord[]){const done=records.filter(r=>r.chapterId===plan.id&&r.status==="COMPLETED"),by=(type:SkillEvidence["evidenceType"])=>done.filter(r=>plan.activities.find(a=>a.id===r.activityId)?.evidenceType===type&&r.score>=plan.gate.minimumScore).length;const independent=by("INDEPENDENT"),transfer=by("TRANSFER"),integration=by("INTEGRATION"),retention=by("RETENTION"),competent=independent>=plan.gate.independent&&transfer>=plan.gate.transfer&&integration>=plan.gate.integration,mastered=competent&&retention>=plan.gate.retention;return {independent,transfer,integration,retention,competent,mastered}}
export function getNextStoryActivity(plan:StoryChapterPlan,records:StoryActivityRecord[],_attempts:Attempt[]):StoryActivitySpec|null{void _attempts;const chapterRecords=records.filter(r=>r.chapterId===plan.id);const failed=chapterRecords.findLast(r=>r.status==="REMEDIATION_REQUIRED");if(failed){const source=plan.activities.find(a=>a.id===failed.activityId)!;const tag=failed.errorTag??"PROCESS";return {...source,id:`${source.id}:remediation`,title:`Targeted repair · ${tag.toLowerCase().replaceAll("_"," ")}`,learningFunction:tag==="ARITHMETIC"?"GUIDED_PRACTICE":"COMPLETION_PROBLEM",kind:"EXERCISE",exerciseId:source.exerciseId??(tag==="SETUP"?"setup-1":"math-margin-1"),guidance:Math.min(4,source.guidance+1) as 0|1|2|3|4,difficulty:Math.max(1,source.difficulty-(tag==="ARITHMETIC"?0:1)) as 1|2|3|4|5,gateContribution:false,why:`The last response showed a ${tag.toLowerCase().replaceAll("_"," ")} error. Repair that cause, then return to the main path.`}}
 return plan.activities.find(a=>!chapterRecords.some(r=>r.activityId===a.id&&r.status==="COMPLETED")&&a.prerequisites.every(id=>chapterRecords.some(r=>r.activityId===id&&r.status==="COMPLETED")))??null}
export function storyStatus(plan:StoryChapterPlan,records:StoryActivityRecord[],manual=false):StoryChapterStatus{if(manual)return "MANUALLY_BYPASSED";const evidence=chapterEvidence(plan,records);if(evidence.mastered)return "PASSED";if(evidence.competent)return plan.gate.retention?"RETENTION_PENDING":"GATE_READY";const next=getNextStoryActivity(plan,records,[]);if(!next)return "GATE_READY";if(next.id.includes("remediation"))return "REMEDIATION";if(next.evidenceType==="INTEGRATION")return "INTEGRATION";if(next.evidenceType==="TRANSFER")return "TRANSFER";if(next.evidenceType==="INDEPENDENT")return "INDEPENDENT";return records.some(r=>r.chapterId===plan.id)?"PRACTICING":"AVAILABLE"}
export function recordStoryActivity(records:StoryActivityRecord[],record:StoryActivityRecord){return [...records.filter(r=>!(r.activityId===record.activityId&&r.status===record.status)),record]}
