"use client";
import { useEffect,useState } from "react";
import { ArrowRight,Check,Clock3,Eye,Lightbulb,LockKeyhole,SquarePen } from "lucide-react";
import type { CaseAction,CaseMode,PublicCaseView } from "@/lib/case-engine";

type CaseSummary={id:string;version:string;title:string;industry:string;difficulty:number;targetMinutes:number;objective:string;poolRole:"TRAINING"|"TRANSFER"|"READINESS_HOLDOUT"};
export type CaseCompletion={caseId:string;title:string;industry:string;completedAt:string;caseVersion:string;mode:CaseMode;poolRole:"TRAINING"|"TRANSFER"|"READINESS_HOLDOUT";calculationAccuracy:number|null;insightCoverage:number;hintsUsed:number};

export function CaseRoom({onComplete,seenCaseIds=[]}:{onComplete?:(result:CaseCompletion)=>void;seenCaseIds?:string[]}){
 const [catalog,setCatalog]=useState<CaseSummary[]>([]),[mode,setMode]=useState<CaseMode>("practice"),[view,setView]=useState<PublicCaseView|null>(null),[evaluation,setEvaluation]=useState<CaseCompletion|null>(null),[error,setError]=useState("");
 useEffect(()=>{fetch("/api/cases").then(r=>r.ok?r.json():Promise.reject(new Error("Unable to load cases"))).then(data=>setCatalog(data.cases)).catch(e=>setError(e.message))},[]);
 async function start(caseId:string){setError("");const response=await fetch("/api/cases",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({caseId,mode})});const data=await response.json();if(!response.ok){setError(data.error);return}setView(data.view)}
 async function act(action:CaseAction){if(!view)return;setError("");const response=await fetch(`/api/cases/${encodeURIComponent(view.sessionId)}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify(action)});const data=await response.json();if(!response.ok){setError(data.error);return}setView(data.view);setEvaluation(data.evaluation);if(data.evaluation)onComplete?.(data.evaluation)}
 if(evaluation)return <CaseReport evaluation={evaluation} leave={()=>{setView(null);setEvaluation(null)}}/>;
 if(!view)return <CaseLobby cases={catalog} mode={mode} setMode={setMode} start={start} error={error} seenCaseIds={seenCaseIds}/>;
 return <ActiveCase view={view} act={act} error={error}/>;
}

function CaseLobby({cases,mode,setMode,start,error,seenCaseIds}:{cases:CaseSummary[];mode:CaseMode;setMode:(m:CaseMode)=>void;start:(id:string)=>void;error:string;seenCaseIds:string[]}){
 return <div className="page case-lobby"><div className="section-title"><div><p className="kicker">Predetermined simulations</p><h1>Choose an unfamiliar decision.</h1><p>Case answers remain on the server. Your argument can change the interview—not the underlying facts.</p></div></div>{error?<p role="alert" className="api-error">{error}</p>:null}
  <div className="mode-switch" aria-label="Case mode">{(["practice","strict","pressure","readiness"] as const).map(m=><button key={m} className={mode===m?"active":""} onClick={()=>setMode(m)}>{m}</button>)}</div>
  <div className="case-list">{cases.filter(c=>mode==="readiness"?c.poolRole==="READINESS_HOLDOUT"&&!seenCaseIds.includes(c.id):c.poolRole!=="READINESS_HOLDOUT").map(c=><article key={c.id}><div><span>{c.industry}</span><small>Difficulty {c.difficulty} · {c.targetMinutes} min</small></div><h2>{c.title}</h2><p>{c.objective}</p><footer><span><LockKeyhole size={14}/> CaseSpec {c.version}</span><button onClick={()=>start(c.id)}>Enter case <ArrowRight size={16}/></button></footer></article>)}</div>{cases.length===0&&!error?<p className="loading-state">Loading validated cases…</p>:mode==="readiness"&&cases.filter(c=>c.poolRole==="READINESS_HOLDOUT"&&!seenCaseIds.includes(c.id)).length===0?<p className="empty-state">No unseen holdout remains. Completed holdouts never count as unseen evidence again.</p>:null}</div>;
}

function ActiveCase({view,act,error}:{view:PublicCaseView;act:(a:CaseAction)=>Promise<void>;error:string}){
 const [input,setInput]=useState(""),[notes,setNotes]=useState(""),[calcAnswer,setCalcAnswer]=useState(""),[equation,setEquation]=useState(""),[unit,setUnit]=useState(""),[insightText,setInsightText]=useState("");
 const pending=view.pendingInsightCount;
 function send(){if(!input.trim())return;void act({type:"message",text:input});setInput("")}
 return <div className="case-shell"><div className="casebar"><div><small>LIVE CASE · {view.mode.toUpperCase()} MODE</small><strong>{view.title}</strong></div><div><Clock3 size={16}/> 34:18 <button onClick={()=>act({type:"finish"})}>End case</button></div></div>
  <div className="objective"><Check size={18}/><span><small>Client objective</small>{view.objective}</span><em>Server-controlled · frozen</em></div>
  <div className="room"><section className="transcript"><div className="stage">{view.stageObjective}</div>{error?<p role="alert" className="api-error">{error}</p>:null}{view.facts.length?<div className="revealed-facts">{view.facts.map(f=><p key={f.id}><Eye size={14}/>{f.text}</p>)}</div>:null}{view.turns.map(t=><div key={t.id} className={`turn ${t.role}`}><span>{t.role==="interviewer"?"Interviewer":t.role==="candidate"?"You":"System"}</span><p>{t.text}</p></div>)}
   {pending>0?<div className="insight-compose"><strong>Submit your analysis</strong><textarea aria-label="Insight reasoning" value={insightText} onChange={e=>setInsightText(e.target.value)} placeholder="State your finding, supporting evidence, implication, and next step…"/><button className="insight-action" disabled={insightText.trim().length<20} onClick={()=>{void act({type:"submit-insight",text:insightText});setInsightText("")}}><SquarePen size={15}/> Submit insight</button></div>:null}
   {view.calculations.map(c=><div className="calculation-box" key={c.id}><strong>{c.prompt}</strong><input aria-label="Equation" placeholder="Equation" value={equation} onChange={e=>setEquation(e.target.value)}/><input aria-label="Calculation answer" inputMode="decimal" placeholder="Answer" value={calcAnswer} onChange={e=>setCalcAnswer(e.target.value)}/><input aria-label="Calculation unit" placeholder="Unit" value={unit} onChange={e=>setUnit(e.target.value)}/><button disabled={!calcAnswer||!equation||!unit} onClick={()=>act({type:"submit-calculation",calculationId:c.id,answer:Number(calcAnswer),equation,unit})}>Submit calculation</button></div>)}
   <div className="case-actions"><button onClick={()=>act({type:"request-hint"})}><Lightbulb size={15}/> Request hint</button><button onClick={()=>act({type:"advance"})}>Advance stage <ArrowRight size={15}/></button></div>
   <div className="composer"><textarea aria-label="Your response" value={input} onChange={e=>setInput(e.target.value)} placeholder="Ask a clarifying question or explain your reasoning…"/><button onClick={send}>Send <ArrowRight size={16}/></button><small>Predetermined truth · hidden answers never enter the browser response</small></div></section>
   <aside className="workspace"><div className="tabs"><button className="active">Scratchpad</button><button>Exhibits <b>{view.exhibits.length}</b></button></div>{view.exhibits.map(e=><figure key={e.id}><figcaption>{e.title}</figcaption><table><thead><tr>{e.columns.map(c=><th key={c}>{c}</th>)}</tr></thead><tbody>{e.rows.map((r,i)=><tr key={i}>{r.map((v,j)=><td key={j}>{v}</td>)}</tr>)}</tbody></table></figure>)}<textarea aria-label="Private scratchpad" value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Private notes — structure, equation, or synthesis…"/><div className="case-integrity"><LockKeyhole size={16}/><span><strong>Closed-world case</strong>Facts cannot change in response to your hypothesis.</span></div></aside></div></div>;
}

function CaseReport({evaluation,leave}:{evaluation:CaseCompletion;leave:()=>void}){return <div className="page case-report"><p className="kicker">Post-case evidence</p><h1>Simulation complete</h1><p>Results are tied to CaseSpec {evaluation.caseVersion}; qualitative review remains separate from deterministic evidence.</p><div className="analytics-summary"><div><span>Calculation accuracy</span><strong>{evaluation.calculationAccuracy===null?"Not observed":`${Math.round(evaluation.calculationAccuracy*100)}%`}</strong><small>exact answer, tolerance, and unit</small></div><div><span>Insight coverage</span><strong>{Math.round(evaluation.insightCoverage*100)}%</strong><small>predetermined scoring targets</small></div><div><span>Hints used</span><strong>{evaluation.hintsUsed}</strong><small>{evaluation.mode} mode</small></div></div><button className="primary" onClick={leave}>Return to case library</button></div>}
