"use client";
import { useEffect,useState } from "react";
import { ArrowRight, ChevronRight, CircleAlert, Clock3 } from "lucide-react";
import { navIcons } from "./icons";
import { buildDailySession, humanTransferGap, learningProfile, safeMinutes, type SessionCandidate } from "@/lib/pedagogy";
import { behavioralQuestions } from "@/lib/seed";
import { SkillLab } from "./skill-lab";
import { calculateReadiness, firmProfiles } from "@/lib/readiness";
import { CaseRoom, type CaseCompletion } from "./case-room";
import { StoryMode } from "./story-mode";
import { exerciseCatalog } from "@/lib/catalog";
import { DiagnosticAssessment } from "./diagnostic-assessment";
import { diagnoseBehavioralStory } from "@/lib/behavioral";
import { applyDiagnostic, initialLearner, loadLearner, recordAttempt, recordCase, exportLearner, type DiagnosticAnswer, type LearnerState, STORE_KEY } from "@/lib/learner";

type View="Today"|"Story mode"|"Skill lab"|"Case room"|"Progress"|"Behavioral"|"Human log"|"Settings";


export function CoachApp(){
 const [state,setState]=useState<LearnerState>(()=>initialLearner()); const [ready,setReady]=useState(false); const [view,setView]=useState<View>("Today"); const [launchExerciseId,setLaunchExerciseId]=useState<string>();
 // Hydrate the versioned external store after mount to avoid a server/client mismatch.
 // eslint-disable-next-line react-hooks/set-state-in-effect
 useEffect(()=>{const loaded=loadLearner(localStorage.getItem(STORE_KEY)??localStorage.getItem("casecraft-learner-v5")??localStorage.getItem("casecraft-learner-v4")??localStorage.getItem("casecraft-learner-v3")??localStorage.getItem("casecraft-v1"));setState(loaded.state);setReady(true)},[]);
 useEffect(()=>{if(ready)localStorage.setItem(STORE_KEY,JSON.stringify(state))},[state,ready]);
 if(!ready)return <main className="loading">Preparing your training plan…</main>;
 if(!state.onboarded)return <Onboarding onDone={(name,minutes,diagnostic)=>{setState(s=>applyDiagnostic(s,name,minutes,diagnostic));setView("Story mode")}}/>;
 if(!state.diagnosticComplete)return <DiagnosticAssessment onAttempt={attempt=>setState(s=>recordAttempt(s,{...attempt,context:"initial diagnostic",guidanceLevel:1,independent:true}))} onComplete={()=>setState(s=>({...s,diagnosticComplete:true}))}/>;
 const props={state,setState,setView,setLaunchExerciseId};
 return <div className="shell"><aside><a className="brand" href="#" onClick={()=>setView("Today")}><span>CC</span>CaseCraft</a><nav aria-label="Primary">{(Object.keys(navIcons) as View[]).map(n=>{const Icon=navIcons[n];return <button className={view===n?"active":""} key={n} onClick={()=>setView(n)}><Icon size={18}/>{n}</button>})}</nav><div className="profile"><div>{state.name.slice(0,2).toUpperCase()}</div><span><strong>{state.name}</strong><small>Interview track</small></span></div></aside><main><Topbar name={state.name} view={view}/>{view==="Today"&&<Today {...props}/>} {view==="Story mode"&&<StoryMode state={state} setState={setState} onAttempt={attempt=>setState(s=>recordAttempt(s,attempt))}/>} {view==="Skill lab"&&<SkillLab exerciseId={launchExerciseId} onFinished={launchExerciseId?()=>{setLaunchExerciseId(undefined);setView("Today")}:undefined} onAttempt={attempt=>setState(s=>recordAttempt(s,attempt))}/>} {view==="Case room"&&<CaseRoom seenCaseIds={state.seenCaseIds} onComplete={(result:CaseCompletion)=>setState(s=>recordCase(s,{id:crypto.randomUUID(),...result,unseen:result.mode==="readiness"&&result.poolRole==="READINESS_HOLDOUT",criticalSkillScore:(result.insightCoverage+(result.calculationAccuracy??result.insightCoverage))/2,hintCount:result.hintsUsed,timingMet:true}))}/>} {view==="Progress"&&<Progress state={state}/>} {view==="Behavioral"&&<Behavioral state={state} setState={setState}/>} {view==="Human log"&&<HumanLog state={state} setState={setState}/>} {view==="Settings"&&<Settings state={state} setState={setState}/>}</main></div>
}
function Onboarding({onDone}:{onDone:(n:string,m:number,d:DiagnosticAnswer)=>void}){const [step,setStep]=useState(0),[name,setName]=useState("Alex"),[minutes,setMinutes]=useState(30),[experience,setExperience]=useState<DiagnosticAnswer["experience"]>("some"),[mathComfort,setMath]=useState<1|2|3|4|5>(3),[structureComfort,setStructure]=useState<1|2|3|4|5>(3);return <main className="onboarding"><div className="onboard-mark">CC</div><div className="step-count">Diagnostic setup · {step+1} of 3</div>{step===0?<section><p className="kicker">Train the reasoning, not the script</p><h1>Your interview coach starts with evidence.</h1><p>We’ll initialize a cautious skill model, then replace self-report with demonstrated performance.</p><label>Your first name<input value={name} onChange={e=>setName(e.target.value)} autoFocus/></label><button className="primary" onClick={()=>setStep(1)}>Continue <ArrowRight size={17}/></button></section>:step===1?<section><p className="kicker">Starting point</p><h1>Tell us what you have practiced.</h1><label>Case experience<select value={experience} onChange={e=>setExperience(e.target.value as DiagnosticAnswer["experience"])}><option value="new">New to cases</option><option value="some">Some practice</option><option value="experienced">Regular practice</option></select></label><label>Math confidence: {mathComfort}/5<input type="range" min="1" max="5" value={mathComfort} onChange={e=>setMath(Number(e.target.value) as 1|2|3|4|5)}/></label><label>Structuring confidence: {structureComfort}/5<input type="range" min="1" max="5" value={structureComfort} onChange={e=>setStructure(Number(e.target.value) as 1|2|3|4|5)}/></label><button className="primary" onClick={()=>setStep(2)}>Set training cadence <ArrowRight size={17}/></button></section>:<section><p className="kicker">A plan that fits the day</p><h1>How long can you usually train?</h1><p>You can change this daily. Every plan mixes correction, retrieval, and transfer.</p><div className="time-grid">{[15,30,45,60,90].map(m=><button className={minutes===m?"selected":""} onClick={()=>setMinutes(m)} key={m}><strong>{m}</strong><span>minutes</span></button>)}</div><button className="primary" onClick={()=>onDone(name,minutes,{experience,mathComfort,structureComfort})}>Open Story Mode <ArrowRight size={17}/></button></section>}</main>}
function Topbar({name,view}:{name:string;view:View}){return <header><div><p>{new Intl.DateTimeFormat("en",{weekday:"long",month:"long",day:"numeric"}).format(new Date())}</p><h2>{view}</h2></div><div className="status"><span></span>Local coach · learning engine v6 <button aria-label="Open profile">{name[0]}</button></div></header>}
type P={state:LearnerState;setState:React.Dispatch<React.SetStateAction<LearnerState>>;setView:(v:View)=>void;setLaunchExerciseId:(id:string|undefined)=>void};
function Today({state,setState,setView,setLaunchExerciseId}:P){
 const today=new Date().toISOString().slice(0,10),firm=firmProfiles.find(f=>f.id===state.targetFirm),readiness=calculateReadiness(state.skills,state.caseHistory,state.humanLogs.map(x=>({evaluatorType:x.evaluatorType,overallScore:3,skillRatings:{}})),firm);
 const ranked=[...state.skills].sort((a,b)=>(1-b.mastery)*(1+b.uncertainty)-(1-a.mastery)*(1+a.uncertainty)).slice(0,6);
 const due=state.reviews.filter(r=>r.nextReview<=today).slice(0,1).map(r=>({id:r.id,skillId:r.skillId,title:`Retrieve: ${r.underlyingErrorPattern.toLowerCase().replaceAll("_"," ")}`,minutes:8,type:"RETRIEVAL" as const,priority:10,why:"A prior reasoning pattern is due. Retrieve it before seeing the explanation.",noveltyGroup:`review-${r.skillId}`}));
 const candidates:SessionCandidate[]=[...due,...ranked.flatMap((skill,i)=>[{id:`target-${skill.id}`,skillId:skill.id,title:skill.observations?`Repair: ${skill.label}`:`Diagnostic: ${skill.label}`,minutes:i===0?12:10,type:"TARGETED" as const,priority:8-i,why:skill.observations?"High combined weakness, uncertainty, and transfer gap.":"Establish real evidence; self-report is not counted as mastery.",noveltyGroup:`skill-${skill.id}`},{id:`link-${skill.id}`,skillId:skill.id,title:`Case Link: apply ${skill.label.toLowerCase()}`,minutes:state.minutes>=45?18:10,type:"INTEGRATED" as const,priority:5-i/10,why:"Test whether isolated reasoning survives inside a client decision.",noveltyGroup:`case-${i%2}`}])];
 if(state.minutes>=45)candidates.push({id:"debrief",skillId:"synthesis",title:"Debrief and rewind",minutes:10,type:"DEBRIEF",priority:4,why:"Correct the highest-value error before the session ends.",noveltyGroup:"reflection"});
 const session=buildDailySession(candidates,state.minutes),focus=state.skills.find(x=>x.id===session.items[0]?.skillId)??state.skills[0];
 return <div className="page"><section className="hero"><div><p className="kicker">Today’s prescription</p><h1>Good morning, {state.name}.</h1><p>{state.attempts.length===0?"Begin with a compact diagnostic, then apply one skill in a case context.":`Your plan targets ${focus.label.toLowerCase()} and its transfer into cases.`}</p></div><div className="readiness"><span>Readiness evidence</span><strong>{readiness.label}</strong><small>{readiness.confidence} confidence · {readiness.evidenceNeeded[0]??"Evidence requirements met"}</small></div></section><section className="plan"><div className="plan-head"><div><h3>{session.targetMinutes}-minute focused session</h3><p>{session.totalMinutes} min planned · retrieval, targeted work, and integration</p></div><select aria-label="Plan duration" value={state.minutes} onChange={e=>setState(x=>({...x,minutes:safeMinutes(e.target.value,30)}))}>{[15,30,45,60,90].map(x=><option key={x} value={x}>{x} minutes</option>)}</select></div>{session.items.map((item,i)=><button className="plan-row" key={item.id} onClick={()=>{if(item.type==="INTEGRATED"){setView("Case room");return}const review=state.reviews.find(r=>r.id===item.id),source=review?state.attempts.find(a=>a.id===review.sourceAttemptId):undefined,candidate=source?exerciseCatalog.find(e=>e.kind===exerciseCatalog.find(x=>x.id===source.exerciseId)?.kind&&e.id!==source.exerciseId&&e.surfaceContext!==source.context):exerciseCatalog.find(e=>e.skill===item.skillId);setLaunchExerciseId(candidate?.id);setView("Skill lab")}}><span className="order">{String(i+1).padStart(2,"0")}</span><span className="activity"><small>{item.type}</small><strong>{item.title}</strong><em>{item.why}</em></span><span className="duration"><Clock3 size={15}/>{safeMinutes(item.minutes)} min</span><ChevronRight size={18}/></button>)}</section><section className="signal-grid"><div className="leverage"><p className="kicker">Highest-leverage improvement</p><h3>{focus.observations?focus.label:"Establish a truthful baseline"}</h3><p>{focus.observations===0?"No performance evidence yet. Complete the diagnostic rather than treating self-confidence as progress.":focus.errors.length?`Root cause: ${focus.errors[0].replaceAll("-"," ")}. Correct it, transfer it, then retrieve it later.`:"The next task tests whether the skill transfers beyond familiar drills."}</p><button onClick={()=>setView("Skill lab")}>Start targeted work <ArrowRight size={16}/></button></div><div className="evidence"><h3>Learning stage</h3><div className="meter-label"><span>{focus.label}</span><b>{learningProfile(focus.id,state.evidence).stage.toLowerCase().replaceAll("_"," ")}</b></div><div className="meter"><i style={{width:`${focus.mastery*100}%`}}/></div><p><CircleAlert size={16}/>{focus.observations===0?"Not introduced; no observed evidence.":`Based on ${focus.observations} attempt${focus.observations===1?"":"s"}; transfer and retention remain separate.`}</p></div></section></div>}
function Progress({state}:{state:LearnerState}){
 const firm=firmProfiles.find(f=>f.id===state.targetFirm),readiness=calculateReadiness(state.skills,state.caseHistory,state.humanLogs.map(x=>({evaluatorType:x.evaluatorType??"peer",overallScore:3,skillRatings:{}})),firm),weak=[...state.skills].sort((a,b)=>a.mastery-b.mastery).slice(0,10),ratings=state.humanLogs.flatMap(log=>Object.entries(log.skillRatings).filter(([id])=>id===weak[0]?.id).map(([,score])=>score)),gap=humanTransferGap(weak[0]?.observations?weak[0].drill:null,ratings);
 const score=(predicate:(item:LearnerState["evidence"][number])=>boolean)=>{const selected=state.evidence.filter(predicate);return selected.length?`${Math.round(selected.reduce((sum,x)=>sum+x.score,0)/selected.length*100)}%`:"Not assessed"};
 const dimensions=[{label:"Assisted practice",value:score(x=>!x.independent),note:"with scaffolds or recent support"},{label:"Independent",value:score(x=>x.independent&&!x.integrated),note:"without strong guidance"},{label:"Transfer",value:score(x=>x.transferDistance>0),note:"changed surface contexts"},{label:"Delayed retention",value:score(x=>x.delayed),note:"retrieved after spacing"},{label:"Simulation",value:readiness.simulationConsistency===null?"Not assessed":`${Math.round(readiness.simulationConsistency*100)}%`,note:"integrated case execution"},{label:"Unseen readiness",value:state.caseHistory.some(x=>x.unseen&&x.mode==="readiness")?"Evidence recorded":"Not assessed",note:"unassisted holdout only"}];
 return <div className="page"><div className="section-title"><div><p className="kicker">Evidence, not activity</p><h1>Your skill model</h1><p>{readiness.label} · {readiness.confidence} confidence. Practice and readiness evidence stay separate.</p></div></div><div className="evidence-dimensions">{dimensions.map(item=><div key={item.label}><span>{item.label}</span><strong>{item.value}</strong><small>{item.note}</small></div>)}</div>{gap?<div className="evidence-needed"><strong>Human-practice transfer gap</strong><p>{gap.message}</p></div>:null}<section className="skill-table"><div className="table-head"><h3>Highest-leverage improvements</h3><span>Stage · evidence range</span></div>{weak.map(skill=>{const profile=learningProfile(skill.id,state.evidence);return <div className="skill-row" key={skill.id}><strong>{skill.label}</strong><div className="meter"><i style={{width:`${skill.mastery*100}%`}}/></div><b>{skill.observations?`${Math.round(skill.mastery*100)}%`:"Not assessed"}</b><span>{profile.stage.toLowerCase().replaceAll("_"," ")}</span><em>{skill.observations?skill.trend:"new"}</em></div>})}</section>{readiness.evidenceNeeded.length?<div className="evidence-needed"><strong>Evidence still needed</strong><ul>{readiness.evidenceNeeded.map(x=><li key={x}>{x}</li>)}</ul></div>:null}</div>}
function Behavioral({state,setState}:{state:LearnerState;setState:React.Dispatch<React.SetStateAction<LearnerState>>}){const [title,setTitle]=useState(""),[context,setContext]=useState(""),[actions,setActions]=useState(""),[result,setResult]=useState(""),[learning,setLearning]=useState("");function save(e:React.FormEvent){e.preventDefault();setState(s=>({...s,stories:[...s.stories,{id:crypto.randomUUID(),title,tags:[],context,objective:"",actions,reasoning:"",obstacles:"",dynamics:"",result,learning,alternatives:[],updatedAt:new Date().toISOString()}]}));setTitle("");setContext("");setActions("");setResult("");setLearning("")}return <div className="page"><div className="section-title"><div><p className="kicker">Behavioral story bank</p><h1>Build stories that survive follow-ups.</h1><p>Diagnostics distinguish your actions, measurable outcomes, specificity, and learning.</p></div></div><div className="behavior-grid"><form onSubmit={save}><h3>Add a story</h3><label>Story title<input value={title} onChange={e=>setTitle(e.target.value)} required/></label><label>Context<textarea value={context} onChange={e=>setContext(e.target.value)} required/></label><label>Your individual actions<textarea value={actions} onChange={e=>setActions(e.target.value)} required placeholder="Use ‘I’ to make ownership explicit."/></label><label>Result<textarea value={result} onChange={e=>setResult(e.target.value)} required/></label><label>Learning<textarea value={learning} onChange={e=>setLearning(e.target.value)} required/></label><button className="primary">Save and diagnose</button></form><section><h3>Story evidence</h3>{state.stories.length?state.stories.map(story=>{const d=diagnoseBehavioralStory({context:story.context,objective:story.objective,actions:story.actions,result:story.result,learning:story.learning});return <article className="story-entry" key={story.id}><div><strong>{story.title}</strong><span>{d.score}/5 anchored score</span></div><p>{d.improvement}</p><small>{d.flags.length?d.flags.join(" · "):"Specific ownership and impact evidenced"}</small><button onClick={()=>setState(s=>({...s,stories:s.stories.filter(x=>x.id!==story.id)}))}>Delete</button></article>}):<p className="empty-state">No stories yet. Add one to receive deterministic feedback.</p>}<h3>Practice prompts</h3>{behavioralQuestions.slice(0,3).map(q=><p className="question" key={q}>{q}</p>)}</section></div></div>}
function HumanLog({state,setState}:Omit<P,"setView"|"setLaunchExerciseId">){const [partner,setPartner]=useState(""),[feedback,setFeedback]=useState(""),[evaluatorType,setEvaluatorType]=useState("peer"),[caseName,setCaseName]=useState(""),[date,setDate]=useState(new Date().toISOString().slice(0,10)),[skillId,setSkillId]=useState("structuring"),[rating,setRating]=useState(3);return <div className="page"><div className="section-title"><div><p className="kicker">External validation loop</p><h1>Log human practice</h1><p>Map outside feedback to a skill so drill-to-human transfer gaps affect the next prescription.</p></div></div><form className="human-form" onSubmit={e=>{e.preventDefault();setState(s=>({...s,humanLogs:[...s.humanLogs,{id:crypto.randomUUID(),partner,date,caseName,style:"hybrid",evaluatorType,skillRatings:{[skillId]:rating},feedback,errors:rating<=2?[`Human-rated ${skillId} gap`]:[],strengths:rating>=4?[skillId]:[]}]}));setPartner("");setFeedback("");setCaseName("")}}><label>Practice partner<input required value={partner} onChange={e=>setPartner(e.target.value)}/></label><label>Date<input type="date" required value={date} onChange={e=>setDate(e.target.value)}/></label><label>Case<input required value={caseName} onChange={e=>setCaseName(e.target.value)}/></label><label>Evaluator type<select value={evaluatorType} onChange={e=>setEvaluatorType(e.target.value)}><option value="peer">Peer applicant</option><option value="experienced-applicant">Experienced applicant</option><option value="consultant">Consultant</option><option value="former-interviewer">Former interviewer / coach</option></select></label><label>Skill observed<select value={skillId} onChange={e=>setSkillId(e.target.value)}>{state.skills.map(skill=><option key={skill.id} value={skill.id}>{skill.label}</option>)}</select></label><label>Rating: {rating}/5<input type="range" min="1" max="5" value={rating} onChange={e=>setRating(Number(e.target.value))}/></label><label className="wide">Overall feedback<textarea required value={feedback} onChange={e=>setFeedback(e.target.value)}/></label><button className="primary">Record human feedback</button></form>{state.humanLogs.length?state.humanLogs.map(x=><div className="log" key={x.id}><strong>{x.caseName} · {x.partner}</strong><p>{x.feedback}</p><span>{x.evaluatorType} · {x.date} · ratings mapped to skill evidence</span></div>):<p className="empty-state">No external practice logged yet. Human evidence remains separate from application evaluation.</p>}</div>}
function Settings({state,setState}:Omit<P,"setView"|"setLaunchExerciseId">){function download(){const blob=new Blob([exportLearner(state)],{type:"application/json"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download="casecraft-backup.json";a.click();URL.revokeObjectURL(url)}async function restore(file:File){const loaded=loadLearner(await file.text());if(confirm("Replace current local data with this backup?"))setState(loaded.state)}return <div className="page"><div className="section-title"><div><p className="kicker">Preferences and privacy</p><h1>Local training settings</h1><p>Your learner data stays in this browser unless you export it.</p></div></div><div className="settings"><label>Default session duration<select value={state.minutes} onChange={e=>setState(s=>({...s,minutes:+e.target.value}))}>{[15,30,45,60,90].map(x=><option key={x} value={x}>{x} minutes</option>)}</select></label><label>Interview date<input type="date" value={state.interviewDate} onChange={e=>setState(s=>({...s,interviewDate:e.target.value}))}/></label><label>Target firm<select value={state.targetFirm??""} onChange={e=>setState(s=>({...s,targetFirm:e.target.value}))}><option value="">General casing</option>{firmProfiles.map(f=><option value={f.id} key={f.id}>{f.name}</option>)}</select></label><div><strong>AI and privacy</strong><p>Local deterministic mode. No paid API, external account, audio upload, or cloud learner storage is used.</p></div><div className="data-actions"><button onClick={download}>Export local backup</button><label className="import-button">Import backup<input type="file" accept="application/json" onChange={e=>{const file=e.target.files?.[0];if(file)void restore(file)}}/></label></div><button className="danger" onClick={()=>{if(confirm("Delete all local CaseCraft data?")){localStorage.removeItem(STORE_KEY);localStorage.removeItem("casecraft-learner-v5");localStorage.removeItem("casecraft-learner-v4");localStorage.removeItem("casecraft-learner-v3");localStorage.removeItem("casecraft-v1");location.reload()}}}>Delete all local data</button></div></div>}
