"use client";
import { useEffect,useState } from "react";
import { ArrowRight, Check, ChevronRight, CircleAlert, Clock3, RotateCcw, Target, X } from "lucide-react";
import { navIcons } from "./icons";
import { chapters, gradeNumber, makePlan, startCase, SkillState, Attempt } from "@/lib/domain";
import { behavioralQuestions, cases, drills, seedSkills } from "@/lib/seed";

type View="Today"|"Story mode"|"Skill lab"|"Case room"|"Progress"|"Behavioral"|"Human log"|"Settings";
type Persist={skills:SkillState[];attempts:Attempt[];onboarded:boolean;name:string;minutes:number;stories:{title:string;ownership:string;result:string}[];humanLogs:{partner:string;feedback:string}[]};
const initial:Persist={skills:seedSkills,attempts:[],onboarded:false,name:"",minutes:30,stories:[],humanLogs:[]};

export function CoachApp(){
 const [state,setState]=useState<Persist>(initial); const [ready,setReady]=useState(false); const [view,setView]=useState<View>("Today");
 // Hydrate the versioned external store after mount to avoid a server/client mismatch.
 // eslint-disable-next-line react-hooks/set-state-in-effect
 useEffect(()=>{const raw=localStorage.getItem("casecraft-v1");if(raw) setState(JSON.parse(raw));setReady(true)},[]);
 useEffect(()=>{if(ready)localStorage.setItem("casecraft-v1",JSON.stringify(state))},[state,ready]);
 if(!ready)return <main className="loading">Preparing your training plan…</main>;
 if(!state.onboarded)return <Onboarding onDone={(name,minutes)=>setState(s=>({...s,name,minutes,onboarded:true}))}/>;
 const props={state,setState,setView};
 return <div className="shell"><aside><a className="brand" href="#" onClick={()=>setView("Today")}><span>CC</span>CaseCraft</a><nav aria-label="Primary">{(Object.keys(navIcons) as View[]).map(n=>{const Icon=navIcons[n];return <button className={view===n?"active":""} key={n} onClick={()=>setView(n)}><Icon size={18}/>{n}</button>})}</nav><div className="profile"><div>{state.name.slice(0,2).toUpperCase()}</div><span><strong>{state.name}</strong><small>Interview track</small></span></div></aside><main><Topbar name={state.name} view={view}/>{view==="Today"&&<Today {...props}/>} {view==="Story mode"&&<Story {...props}/>} {view==="Skill lab"&&<Lab {...props}/>} {view==="Case room"&&<CaseRoom/>} {view==="Progress"&&<Progress state={state}/>} {view==="Behavioral"&&<Behavioral state={state} setState={setState}/>} {view==="Human log"&&<HumanLog state={state} setState={setState}/>} {view==="Settings"&&<Settings state={state} setState={setState}/>}</main></div>
}
function Onboarding({onDone}:{onDone:(n:string,m:number)=>void}){const [step,setStep]=useState(0),[name,setName]=useState("Alex"),[minutes,setMinutes]=useState(30);return <main className="onboarding"><div className="onboard-mark">CC</div><div className="step-count">Diagnostic setup · {step+1} of 2</div>{step===0?<section><p className="kicker">Train the reasoning, not the script</p><h1>Your interview coach starts with evidence.</h1><p>We’ll build a granular model of your skills and prescribe the highest-leverage practice—not count completed cases.</p><label>Your first name<input value={name} onChange={e=>setName(e.target.value)} autoFocus/></label><button className="primary" onClick={()=>setStep(1)}>Set training cadence <ArrowRight size={17}/></button></section>:<section><p className="kicker">A plan that fits the day</p><h1>How long can you usually train?</h1><p>You can change this daily. Every plan mixes correction, retrieval, and transfer.</p><div className="time-grid">{[15,30,45,60,90].map(m=><button className={minutes===m?"selected":""} onClick={()=>setMinutes(m)} key={m}><strong>{m}</strong><span>minutes</span></button>)}</div><button className="primary" onClick={()=>onDone(name||"Candidate",minutes)}>Build my diagnostic <ArrowRight size={17}/></button></section>}</main>}
function Topbar({name,view}:{name:string;view:View}){return <header><div><p>{new Intl.DateTimeFormat("en",{weekday:"long",month:"long",day:"numeric"}).format(new Date())}</p><h2>{view}</h2></div><div className="status"><span></span>Demo coach online <button aria-label="Open profile">{name[0]}</button></div></header>}
type P={state:Persist;setState:React.Dispatch<React.SetStateAction<Persist>>;setView:(v:View)=>void};
function Today({state,setState,setView}:P){const today=new Date().toISOString().slice(0,10);const plan=makePlan(state.skills,state.minutes,today);const focus=state.skills.find(x=>x.id===plan[0]?.skill)!;return <div className="page"><section className="hero"><div><p className="kicker">Today’s prescription</p><h1>Good morning, {state.name}.</h1><p>Your setup is improving in drills, but it is not transferring reliably into cases. Today closes that gap.</p></div><div className="readiness"><span>Readiness evidence</span><strong>Developing</strong><small>Moderate uncertainty · 3 unseen cases needed</small></div></section><section className="plan"><div className="plan-head"><div><h3>{state.minutes}-minute focused session</h3><p>Selected from mastery, due reviews, and case-transfer evidence.</p></div><select aria-label="Plan duration" value={state.minutes} onChange={e=>setState(s=>({...s,minutes:+e.target.value}))}>{[15,30,45,60,90].map(x=><option key={x}>{x}</option>)}</select></div>{plan.map((p,i)=><button className="plan-row" key={p.skill} onClick={()=>setView(i===plan.length-1?"Case room":"Skill lab")}><span className="order">{String(i+1).padStart(2,"0")}</span><span className="activity"><small>{i===0?"REWIND & RETRY":i===plan.length-1?"TRANSFER":"SKILL LAB"}</small><strong>{p.title}</strong><em>{p.why}</em></span><span className="duration"><Clock3 size={15}/>{p.minutes} min</span><ChevronRight size={18}/></button>)}</section><section className="signal-grid"><div className="leverage"><p className="kicker">Highest-leverage improvement</p><h3>State the equation before touching the numbers.</h3><p>In 3 of your last 5 integrated attempts, arithmetic was accurate but the setup solved the wrong question.</p><button onClick={()=>setView("Skill lab")}>Start targeted correction <ArrowRight size={16}/></button></div><div className="evidence"><h3>Skill evidence</h3><div className="meter-label"><span>{focus.label}</span><b>{Math.round(focus.mastery*100)}% range</b></div><div className="meter"><i style={{width:`${focus.mastery*100}%`}}/></div><p><CircleAlert size={16}/>Uncertainty is elevated because only two independent observations exist.</p></div></section></div>}
function Story({setView}:P){return <div className="page story"><div className="section-title"><div><p className="kicker">Adaptive curriculum</p><h1>Your path to interview readiness</h1><p>Branches appear when evidence says a skill needs repair. You can continue, but unresolved gaps stay visible.</p></div><div className="legend"><span><i className="done"/>Demonstrated</span><span><i className="current"/>Current</span><span><i/>Upcoming</span></div></div><div className="story-map">{chapters.map((c,i)=><div className={`chapter ${i<2?"complete":i===2?"now":""}`} key={c[0]}><span className="node">{i<2?<Check/>:i+1}</span><div><small>{c[2]}</small><h3>{c[1]}</h3><p>{i===2?"Mastery gate: build and prioritize a tailored issue tree.":i<2?"Mastery gate passed with consistent independent evidence.":"Unlocks when prerequisite evidence is sufficient."}</p>{i===2&&<button onClick={()=>setView("Skill lab")}>Continue chapter <ArrowRight size={15}/></button>}</div>{i===2&&<aside className="remediation"><RotateCcw size={16}/><span><strong>Remediation branch</strong>Quantitative setup · 2 drills due</span></aside>}</div>)}</div></div>}
function Lab({setState}:P){const [idx,setIdx]=useState(0),[answer,setAnswer]=useState(""),[result,setResult]=useState<null|ReturnType<typeof gradeNumber>>(null),[attemptNo,setAttemptNo]=useState(1);const d=drills[idx%drills.length];function submit(){const g=gradeNumber(Number(answer),d.answer,d.tolerance);setResult(g);const a:Attempt={id:crypto.randomUUID(),exerciseId:d.id,skill:d.skill,answer,correct:g.correct,score:g.score,at:new Date().toISOString(),attemptNo,errorTag:g.correct?undefined:"calculation-error"};setState(s=>({...s,attempts:[...s.attempts,a]}))}function next(){setIdx(x=>x+1);setAnswer("");setResult(null);setAttemptNo(1)}return <div className="page lab"><div className="lab-top"><div><p className="kicker">Quantitative setup · Guidance 2</p><h1>Solve the right question first.</h1></div><span>Exercise {idx+1} of 3</span></div><div className="exercise"><div className="prompt"><span>Client prompt</span><h2>{d.prompt}</h2><div className="setup"><strong>Required setup</strong><p>{d.setup}</p></div></div><div className="answer"><label>Your answer<div><input inputMode="decimal" value={answer} onChange={e=>setAnswer(e.target.value)} placeholder="Enter a number"/><span>{d.unit}</span></div></label>{!result?<button className="primary" onClick={submit} disabled={!answer}>Check reasoning</button>:<div className={`feedback ${result.correct?"good":"bad"}`}><h3>{result.correct?<><Check/>Correct setup and execution</>:<><X/>Not yet—rewind this step</>}</h3><p>{result.correct?d.implication:`The reference answer is ${d.answer} ${d.unit}. Check the equation and units before recalculating.`}</p>{!result.correct&&attemptNo===1?<button onClick={()=>{setResult(null);setAnswer("");setAttemptNo(2)}}><RotateCcw size={16}/>Rewind & retry</button>:<button onClick={next}>Try an analogous problem <ArrowRight size={16}/></button>}</div>}<p className="attempt-note">Every attempt is retained. Your retry is compared with attempt one and scheduled for review.</p></div></div></div>}
function CaseRoom(){const spec=cases[0];const [runtime,setRuntime]=useState(()=>startCase(spec));const [input,setInput]=useState("");const [notes,setNotes]=useState("");function send(){if(!input.trim())return;const low=input.toLowerCase();let reply="I don’t have that information. What would you like to examine next?";if(low.includes("objective"))reply=spec.objective;else if(low.includes("volume")&&runtime.stage==="analysis")reply=spec.clientFacts[0].text;else if(low.includes("competitor"))reply="The competitor’s internal forecast is unavailable.";else if(low.includes("structure"))reply="Please walk me through your structure and where you would start.";setRuntime(r=>({...r,turns:[...r.turns,{role:"candidate",text:input},{role:"interviewer",text:reply}]}));setInput("")}return <div className="case-shell"><div className="casebar"><div><small>LIVE CASE · PRACTICE MODE</small><strong>{spec.title}</strong></div><div><Clock3 size={16}/> 34:18 <button>End case</button></div></div><div className="objective"><Target size={18}/><span><small>Client objective</small>{spec.objective}</span><em>CaseSpec {spec.version} · frozen</em></div><div className="room"><section className="transcript"><div className="stage">Stage 1 · Clarification and structure</div>{runtime.turns.map((t,i)=><div key={i} className={`turn ${t.role}`}><span>{t.role==="interviewer"?"Interviewer":"You"}</span><p>{t.text}</p></div>)}<div className="composer"><textarea aria-label="Your response" value={input} onChange={e=>setInput(e.target.value)} placeholder="Ask a clarifying question or explain your reasoning…"/><button onClick={send}>Send <ArrowRight size={16}/></button><small>Predetermined case truth · interviewer wording may vary</small></div></section><aside className="workspace"><div className="tabs"><button className="active">Scratchpad</button><button>Exhibits <b>0</b></button></div><textarea aria-label="Private scratchpad" value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Private notes — try a structure, equation, or synthesis…"/><div className="case-integrity"><Check size={16}/><span><strong>Closed-world case</strong>Facts cannot change in response to your hypothesis.</span></div></aside></div></div>}
function Progress({state}:{state:Persist}){const weak=[...state.skills].sort((a,b)=>a.mastery-b.mastery).slice(0,10);return <div className="page"><div className="section-title"><div><p className="kicker">Evidence, not activity</p><h1>Your skill model</h1><p>Ranges reflect uncertainty across drills, cases, difficulty, and evaluator source.</p></div></div><div className="analytics-summary"><div><span>Critical skills stable</span><strong>7 / 12</strong><small>across independent attempts</small></div><div><span>Retry improvement</span><strong>+18 pts</strong><small>attempt 1 → attempt 2</small></div><div><span>Hint dependence</span><strong>Low</strong><small>down over 4 sessions</small></div></div><section className="skill-table"><div className="table-head"><h3>Highest-leverage improvements</h3><span>Mastery range · uncertainty</span></div>{weak.map(s=><div className="skill-row" key={s.id}><strong>{s.label}</strong><div className="meter"><i style={{width:`${s.mastery*100}%`}}/></div><b>{Math.round(s.mastery*100)}%</b><span>±{Math.round(s.uncertainty*100)}</span><em>{s.trend}</em></div>)}</section></div>}
function Behavioral({setState}:{state:Persist;setState:React.Dispatch<React.SetStateAction<Persist>>}){const [title,setTitle]=useState(""),[ownership,setOwnership]=useState(""),[result,setResult]=useState("");return <div className="page"><div className="section-title"><div><p className="kicker">Behavioral story bank</p><h1>Build stories that survive follow-ups.</h1><p>Capture your individual choices, interpersonal dynamics, quantified result, and learning.</p></div></div><div className="behavior-grid"><form onSubmit={e=>{e.preventDefault();setState(s=>({...s,stories:[...s.stories,{title,ownership,result}]}));setTitle("");setOwnership("");setResult("")}}><h3>Add a story</h3><label>Story title<input value={title} onChange={e=>setTitle(e.target.value)} required/></label><label>Your individual actions<textarea value={ownership} onChange={e=>setOwnership(e.target.value)} required placeholder="Use ‘I’ to make ownership explicit."/></label><label>Result and learning<textarea value={result} onChange={e=>setResult(e.target.value)} required/></label><button className="primary">Save to Story Bank</button></form><section><h3>Realistic follow-ups</h3>{behavioralQuestions.map(q=><p className="question" key={q}>{q}</p>)}<p className="ownership-flag"><CircleAlert size={16}/> Answers with repeated “we” language are flagged for unclear ownership.</p></section></div></div>}
function HumanLog({state,setState}:Omit<P,"setView">){const [partner,setPartner]=useState(""),[feedback,setFeedback]=useState("");return <div className="page"><div className="section-title"><div><p className="kicker">Calibration</p><h1>Log external practice</h1><p>Human feedback stays visibly attributed and is weighted by evaluator experience.</p></div></div><form className="human-form" onSubmit={e=>{e.preventDefault();setState(s=>({...s,humanLogs:[...s.humanLogs,{partner,feedback}]}));setPartner("");setFeedback("")}}><label>Practice partner<input required value={partner} onChange={e=>setPartner(e.target.value)}/></label><label>Evaluator type<select><option>Peer applicant</option><option>Experienced applicant</option><option>Consultant</option><option>Former interviewer / coach</option></select></label><label className="wide">Overall feedback<textarea required value={feedback} onChange={e=>setFeedback(e.target.value)}/></label><button className="primary">Record human feedback</button></form>{state.humanLogs.map((x,i)=><div className="log" key={i}><strong>{x.partner}</strong><p>{x.feedback}</p><span>Human evaluation · source retained</span></div>)}</div>}
function Settings({state,setState}:Omit<P,"setView">){return <div className="page"><div className="section-title"><div><p className="kicker">Preferences</p><h1>Training settings</h1></div></div><div className="settings"><label>Default session duration<select value={state.minutes} onChange={e=>setState(s=>({...s,minutes:+e.target.value}))}>{[15,30,45,60,90].map(x=><option key={x}>{x} minutes</option>)}</select></label><div><strong>AI status</strong><p>Demo deterministic mode. No API key required; the immutable case engine and grading remain available.</p></div><button className="danger" onClick={()=>{localStorage.removeItem("casecraft-v1");location.reload()}}>Reset demo data</button></div></div>}
