"use client";
import {useMemo,useState} from "react";
import {ArrowRight,Check,Eye,RotateCcw,X} from "lucide-react";
import {exerciseCatalog,type ExerciseKind} from "@/lib/catalog";
import {evaluateExercise,type ExerciseFeedback} from "@/lib/exercise-engine";
import type {Attempt} from "@/lib/domain";
import type {ConfidenceJudgment} from "@/lib/pedagogy";
import {VerbalPractice} from "./verbal-practice";

const labels:Record<ExerciseKind,string>={"mental-math":"Mental math","quant-setup":"Quant setup",structure:"Structuring",exhibit:"Exhibits",brainstorm:"Brainstorming",synthesis:"Synthesis"};
const pretty=(value:string)=>value.toLowerCase().replaceAll("_"," ");
function expertStep(exercise:(typeof exerciseCatalog)[number]){if(typeof exercise.answer!=="number")return exercise.rationale;const formulas:Record<string,string>={margin:"Operating margin = (revenue − costs) ÷ revenue",growth:"Growth = (new value − old value) ÷ old value",breakeven:"Break-even volume = fixed costs ÷ contribution per unit",weighted:"Weighted result = sum of each value × its weight",utilization:"Utilization = output ÷ available capacity",share:"Market share = client sales ÷ total market"};return `${formulas[exercise.deepPrinciple]??"Set up the required relationship"}. The result is ${exercise.answer} ${exercise.unit??""}. Round only after completing the calculation, then explain what it means for the client.`}
export function SkillLab({onAttempt,exerciseId,onFinished}:{onAttempt:(attempt:Attempt)=>void;exerciseId?:string;onFinished?:(correct:boolean,errorTag?:string)=>void}){
 const [kind,setKind]=useState<ExerciseKind>("mental-math"),[index,setIndex]=useState(0),[response,setResponse]=useState(""),[feedback,setFeedback]=useState<ExerciseFeedback|null>(null),[attemptNo,setAttemptNo]=useState(1),[confidence,setConfidence]=useState<ConfidenceJudgment>("MEDIUM"),[revealed,setRevealed]=useState(false);
 const pool=useMemo(()=>exerciseId?exerciseCatalog.filter(e=>e.id===exerciseId):exerciseCatalog.filter(e=>e.kind===kind),[kind,exerciseId]),exercise=pool[index%pool.length],activeExample=["WORKED_EXAMPLE","PREDICTION_EXAMPLE"].includes(exercise.learningFunction);
 function submit(){const result=evaluateExercise(exercise,response);setFeedback(result);onAttempt({id:crypto.randomUUID(),exerciseId:exercise.id,skill:exercise.skill,answer:response,correct:result.correct,score:result.score,at:new Date().toISOString(),attemptNo,errorTag:result.errorTags[0],guidanceLevel:exercise.guidance,hintsUsed:revealed?1:0,independent:exercise.guidance<=1&&!revealed,transferDistance:exercise.transferDistance,integrated:exercise.learningFunction==="INTEGRATED_CASE_SEGMENT",context:exercise.surfaceContext,confidence,learningFunction:exercise.learningFunction})}
 function reset(nextIndex=index){setIndex(nextIndex);setResponse("");setFeedback(null);setAttemptNo(1);setRevealed(false);setConfidence("MEDIUM")}
 function choose(next:ExerciseKind){setKind(next);reset(0)}
 return <div className="page lab"><div className="lab-top"><div><p className="kicker">Skill Lab · {pretty(exercise.learningFunction)}</p><h1>Model, solve, then transfer.</h1><p>{exercise.deepPrinciple} · {exercise.surfaceContext}</p></div><span>{index+1} / {pool.length} · difficulty {exercise.difficulty} · {exercise.estimatedDuration} min</span></div>
  {!exerciseId?<div className="lab-kind" aria-label="Exercise type">{(Object.keys(labels) as ExerciseKind[]).map(k=><button className={kind===k?"active":""} key={k} onClick={()=>choose(k)}>{labels[k]}</button>)}</div>:null}
  <div className="exercise"><div className="prompt"><span>{labels[exercise.kind]} · guidance {exercise.guidance}</span><h2>{exercise.prompt}</h2><div className="setup"><strong>{activeExample?"Prediction pause":"Evaluation focus"}</strong><p>{activeExample?"Commit to your next step before revealing the expert reasoning.":exercise.rationale}</p>{activeExample&&!revealed?<button onClick={()=>setRevealed(true)}><Eye size={15}/> Reveal expert step</button>:activeExample?<p className="expert-reveal">{expertStep(exercise)}</p>:null}</div></div>
   <div className="answer">{typeof exercise.answer!=="number"?<VerbalPractice/>:null}<label>Your {activeExample?"prediction":"response"}{typeof exercise.answer==="number"?<input inputMode="decimal" value={response} onChange={e=>setResponse(e.target.value)} placeholder="Enter a number"/>:<textarea value={response} onChange={e=>setResponse(e.target.value)} placeholder="Explain your reasoning, priority, and implication…"/>}</label>
    {exercise.assessmentEligibility?<fieldset className="confidence"><legend>Confidence before feedback</legend>{(["LOW","MEDIUM","HIGH"] as const).map(x=><button type="button" aria-pressed={confidence===x} className={confidence===x?"selected":""} onClick={()=>setConfidence(x)} key={x}>{x.toLowerCase()}</button>)}</fieldset>:null}
    {!feedback?<button className="primary" onClick={submit} disabled={!response.trim()}>Evaluate response</button>:<div className={`feedback ${feedback.correct?"good":"bad"}`}><h3>{feedback.correct?<><Check/>Correct</>:<><X/>Needs another pass</>}</h3><p>{feedback.improvement}</p><small>{feedback.evidence.join(" · ")}</small>{!feedback.correct&&attemptNo===1?<button onClick={()=>{setFeedback(null);setResponse("");setAttemptNo(2)}}><RotateCcw size={16}/>Redo the same segment</button>:<button onClick={()=>onFinished?onFinished(feedback.correct,feedback.errorTags[0]):reset(index+1)}>{onFinished?"Continue Story":"Analogous transfer"} <ArrowRight size={16}/></button>}</div>}
    <p className="attempt-note">Attempt A → diagnose → minimal correction → Attempt B → transfer → delayed retrieval.</p></div></div></div>
}
