"use client";

import { ArrowRight, Check, Clock3 } from "lucide-react";
import { VerbalPractice } from "./verbal-practice";
import { assessWelcomeResponse, isNumericAnswer, northstarTruth as truth, welcomeObservations, welcomeStageLabels, type WelcomeCaseState, type WelcomeSignal } from "@/lib/welcome-case";

type Props={state:WelcomeCaseState;onChange:(state:WelcomeCaseState)=>void;onFinish:()=>void;onSkip:()=>void};
const money=(n:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(n);

export function WelcomeCase({state,onChange,onFinish,onSkip}:Props){
 const update=(patch:Partial<WelcomeCaseState>)=>onChange({...state,...patch});
 if(state.status==="NOT_STARTED")return <main className="welcome-intro"><section><p className="kicker">Your first case</p><h1>See how a consulting case actually works.</h1><p>You’ll work through a short case from the client question to the final recommendation. We’ll explain each step as you go, and you’ll make a few decisions yourself.</p><div className="welcome-time"><Clock3 size={18}/><strong>About 12–15 minutes</strong></div><button className="primary" onClick={()=>update({status:"IN_PROGRESS",startedAt:new Date().toISOString()})}>Start your first case <ArrowRight size={17}/></button><small>No case experience needed.</small><button className="welcome-skip" onClick={onSkip}>Already experienced with case interviews? Skip the walkthrough</button></section></main>;
 const answer=(key:string,value:string)=>update({answers:{...state.answers,[key]:value},draft:value});
 const signal=(item:WelcomeSignal)=>state.signals.some(x=>x.skillId===item.skillId)?state.signals: [...state.signals,item];
 const submit=(key:string,item?:WelcomeSignal)=>update({answers:{...state.answers,[key]:state.draft},phase:"FEEDBACK",signals:item?signal(item):state.signals});
 const next=()=>update({stage:Math.min(9,state.stage+1),step:0,phase:"QUESTION",draft:""});
 const shell=(body:React.ReactNode)=><main className="welcome-shell"><header><div><small>Your first case</small><strong>Northstar Coffee</strong></div><span>{state.stage+1} of 10</span></header><nav aria-label="Case progress">{welcomeStageLabels.map((label,i)=><span key={label} className={i<state.stage?"done":i===state.stage?"current":""}>{i<state.stage?<Check size={12}/>:i+1}<small>{label}</small></span>)}</nav><div className="welcome-layout"><section className="welcome-main">{body}</section><aside><p className="kicker">Case facts</p><h3>Northstar Coffee</h3><p>Regional premium coffee chain with 14 Northeast locations.</p>{state.stage>=1&&<Fact label="Success threshold" value="$200K annual operating profit"/>}{state.stage>=4&&<><Fact label="Weekday traffic" value="600 transactions/day"/><Fact label="Weekend traffic" value="350 transactions/day"/><Fact label="Average ticket" value="$8.00"/><Fact label="Variable costs" value="35% of revenue"/><Fact label="Annual fixed costs" value="$650,000"/></>}{state.stage>=7&&<Fact label="Key uncertainty" value="Volatile office-worker traffic"/>}</aside></div></main>;
 const feedback=(title:string,copy:React.ReactNode)=><div className="welcome-feedback"><strong><Check size={17}/>{title}</strong>{copy}<button className="primary" onClick={next}>Continue <ArrowRight size={16}/></button></div>;
 if(state.stage===0)return shell(<><Stage title="The Client Question">Northstar Coffee operates 14 premium coffee shops across the Northeast. Management is considering opening a location in a dense downtown business district.<br/><br/>They’ve asked us whether they should open the store.</Stage>{state.phase==="QUESTION"?<Response label="Before doing any analysis, what do you think an experienced candidate should clarify?" value={state.draft} onChange={v=>update({draft:v})} onSubmit={()=>submit("client-question",{skillId:"clarifying-questions",quality:assessWelcomeResponse("clarify",state.draft)})}/>:feedback("Good case habit",<><p>Before solving anything, make sure you understand the decision the client is actually trying to make.</p><blockquote>Management wants the location to generate at least $200,000 in annual operating profit once stabilized.</blockquote><p>Without that target, we could calculate profit but still would not know whether the result is good enough.</p></>)}</>);
 if(state.stage===1)return shell(<><Stage title="Clarify the Objective">Which question would be MOST useful before building your analysis?</Stage>{state.phase==="QUESTION"?<Choices value={state.draft} onChoose={v=>answer("objective",v)} options={["What coffee drinks does Northstar currently sell?","What annual operating profit would make the new location attractive?","Who founded Northstar?","What color scheme will the new store use?"]} onSubmit={()=>submit("objective",{skillId:"problem-definition",quality:state.draft==="1"?2:0})}/>:feedback(state.answers.objective==="1"?"Exactly":"The second question is most useful",<><p>A useful clarifying question changes how you analyze or evaluate the problem.</p><div className="concept-grid"><b>Decision<small>What must the client decide?</small></b><b>Metric<small>How is success measured?</small></b><b>Horizon<small>Over what period?</small></b><b>Constraint<small>What requirement matters?</small></b></div></>)}</>);
 if(state.stage===2){
  if(state.step===1)return shell(<><Stage title="Structure the Problem">If you could investigate only ONE branch first, which would you choose and why?</Stage>{state.phase==="QUESTION"?<Response label="Choose a branch and connect it to Northstar’s decision." value={state.draft} onChange={v=>update({draft:v})} onSubmit={()=>submit("structure-priority",{skillId:"prioritization",quality:assessWelcomeResponse("priority",state.draft)})}/>:feedback("Prioritize from the objective",<p>Store economics or revenue potential is the strongest starting point because Northstar’s explicit threshold is financial. We first need to know whether the opportunity is economically viable.</p>)}</>);
  return shell(<><Stage title="Structure the Problem">Which structure would you use to answer the client’s question?</Stage>{state.phase==="QUESTION"?<Choices value={state.draft} onChoose={v=>answer("structure",v)} options={["Revenue potential · Cost economics · Strategic risks","Customers · Coffee · Competitors · Company","Revenue · Sales · Customers · Market size · Rent · Costs"]} onSubmit={()=>submit("structure",{skillId:"structuring",quality:state.draft==="0"?2:0})}/>:<div className="welcome-feedback"><strong><Check size={17}/>{state.answers.structure==="0"?"Decision-led structure":"Structure A is strongest"}</strong><p><b>A</b> directly tests earnings, profitability, and risks. B is generic; C overlaps revenue, sales, customers, and market size.</p><pre className="issue-tree">SHOULD NORTHSTAR OPEN?{`\n`}├─ Revenue potential — customer volume, average spend{`\n`}├─ Cost economics — variable costs, fixed costs{`\n`}└─ Strategic considerations — demand, competition, operations</pre><p>Strong structures organize analysis around the client decision—not a memorized list.</p><button className="primary" onClick={()=>update({step:1,phase:"QUESTION",draft:""})}>Continue</button></div>}</>);
 }
 if(state.stage===3)return shell(<><Stage title="Prioritize">Northstar needs $200,000 of annual operating profit. Which question should we answer first?</Stage>{state.phase==="QUESTION"?<Choices value={state.draft} onChoose={v=>answer("prioritize",v)} options={["Can projected store economics exceed the profit threshold?","Could Northstar redesign its loyalty program?","Should Northstar add more seasonal drinks?","Could the company expand internationally later?"]} onSubmit={()=>submit("prioritize",{skillId:"prioritization",quality:state.draft==="0"?2:0})}/>:feedback(state.answers.prioritize==="0"?"Right priority":"Start with the economics",<p>You don’t have to analyze every branch equally. The case objective determines what deserves attention first.</p>)}</>);
 if(state.stage===4)return shell(<SetupAnalysis state={state} onChange={onChange} onNext={next}/>);
 if(state.stage===5)return shell(<Calculation state={state} onChange={onChange} onNext={next}/>);
 if(state.stage===6)return shell(<Exhibit state={state} onChange={onChange} onNext={next}/>);
 if(state.stage===7)return shell(<><Stage title="Synthesize">The interviewer stops you: “So where are you at right now?” Give a 2–4 sentence answer.</Stage>{state.phase==="QUESTION"?<Response label="Your interim synthesis" value={state.draft} onChange={v=>update({draft:v})} onSubmit={()=>submit("synthesis",{skillId:"synthesis",quality:assessWelcomeResponse("synthesis",state.draft)})}/>:feedback("Synthesis advances the case",<><p><b>Finding:</b> projected profit is about $350K. <b>Implication:</b> it exceeds the $200K target. <b>Updated view:</b> evidence supports opening. <b>Next question:</b> validate office-traffic durability.</p><p>A synthesis is not a recap; it says what we learned, what it means, what we believe, and what comes next.</p></>)}</>);
 if(state.stage===8)return shell(<><Stage title="Recommend">The CEO asks: “Should we open the downtown location?” Give your recommendation in approximately 30–60 seconds.</Stage>{state.phase==="QUESTION"?<><VerbalPractice/><Response label="Your recommendation" value={state.draft} onChange={v=>update({draft:v})} onSubmit={()=>submit("recommendation",{skillId:"recommendation",quality:assessWelcomeResponse("recommendation",state.draft)})}/></>:feedback("A supported recommendation",<><p><b>Recommendation:</b> Proceed, subject to validating office-worker demand. <b>Evidence:</b> $350K profit is about $150K above target, and downtown comparables generate about $390K.</p><p><b>Risk:</b> volatile office traffic. <b>Next step:</b> validate foot traffic and stress-test profit before signing the lease.</p></>)}</>);
 return shell(<Debrief state={state} onFinish={onFinish}/>);
}

function Stage({title,children}:{title:string;children:React.ReactNode}){return <div className="welcome-stage"><p className="kicker">Northstar Coffee</p><h1>{title}</h1><div>{children}</div></div>}
function Fact({label,value}:{label:string;value:string}){return <div className="welcome-fact"><small>{label}</small><strong>{value}</strong></div>}
function Response({label,value,onChange,onSubmit,placeholder="Write what you would say…"}:{label:string;value:string;onChange:(v:string)=>void;onSubmit:()=>void;placeholder?:string}){return <div className="welcome-question"><label>{label}<textarea value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder}/></label><button className="primary" disabled={!value.trim()} onClick={onSubmit}>Commit response <ArrowRight size={16}/></button></div>}
function Choices({options,value,onChoose,onSubmit}:{options:string[];value:string;onChoose:(v:string)=>void;onSubmit:()=>void}){return <div className="welcome-choices">{options.map((x,i)=><button key={x} className={value===String(i)?"selected":""} onClick={()=>onChoose(String(i))}><b>{String.fromCharCode(65+i)}</b>{x}</button>)}<button className="primary" disabled={!value} onClick={onSubmit}>Commit choice</button></div>}

function SetupAnalysis({state,onChange,onNext}:{state:WelcomeCaseState;onChange:(s:WelcomeCaseState)=>void;onNext:()=>void}){const fields=[["setup-transactions","Annual transactions ="],["setup-revenue","Annual revenue ="],["setup-profit","Operating profit ="]] as const;const combined=fields.map(([key])=>state.answers[key]??"").join(" ");const submit=()=>onChange({...state,phase:"FEEDBACK",signals:[...state.signals,{skillId:"quant-setup",quality:assessWelcomeResponse("setup",combined)}]});return <><Stage title="Set Up the Analysis">Before calculating anything, how would you determine annual operating profit?</Stage>{state.phase==="QUESTION"?<div className="setup-fields">{fields.map(([key,label])=><label key={key}>{label}<input value={state.answers[key]??""} onChange={e=>onChange({...state,answers:{...state.answers,[key]:e.target.value}})} placeholder="Formula or words"/></label>)}<button className="primary" disabled={fields.some(([key])=>!state.answers[key]?.trim())} onClick={submit}>Commit setup</button></div>:<div className="welcome-feedback"><strong><Check size={17}/>Setup before arithmetic</strong><p>Annual transactions = weekly transactions × 52. Annual revenue = annual transactions × average ticket.</p><p>Operating profit = revenue × (1 − 35%) − fixed costs. This separates choosing the right equation from executing the arithmetic.</p><button className="primary" onClick={onNext}>Continue</button></div>}</>}
function Calculation({state,onChange,onNext}:{state:WelcomeCaseState;onChange:(s:WelcomeCaseState)=>void;onNext:()=>void}){
 const questions=[{q:"How many transactions does the store generate in a typical week?",a:truth.weeklyTransactions,h:"Multiply weekday traffic by 5 and weekend traffic by 2, then add."},{q:"How many transactions is that per year?",a:truth.annualTransactions,h:"Multiply weekly transactions by 52."},{q:"What is annual revenue?",a:truth.annualRevenue,h:"Multiply annual transactions by the $8 average ticket."},{q:"What is annual operating profit?",a:truth.operatingProfit,h:"Keep 65% of revenue after variable costs, then subtract $650K."}];
 if(state.step===4){const quality=assessWelcomeResponse("implication",state.draft);return <><Stage title="Calculate">Northstar’s target is $200,000. What does the result tell us?</Stage>{state.phase==="QUESTION"?<Response label="Complete the calculation with its business implication." value={state.draft} onChange={v=>onChange({...state,draft:v})} onSubmit={()=>onChange({...state,phase:"FEEDBACK",answers:{...state.answers,implication:state.draft},signals:[...state.signals,{skillId:"quant-interpretation",quality}]})}/>:<div className="welcome-feedback"><strong><Check size={17}/>Calculation → interpretation</strong><p>The store exceeds the target by {money(truth.targetSurplus)}, so the initial economics support opening. A number without its implication is incomplete.</p><button className="primary" onClick={onNext}>Continue</button></div>}</>}
 const item=questions[state.step], key=`calc-${state.step}`, count=state.attempts[key]??0, correct=isNumericAnswer(state.draft,item.a,1);
 if(state.phase==="FEEDBACK")return <><Stage title="Calculate">{item.q}</Stage><div className="welcome-feedback"><strong>Worked correction</strong><p>{item.h} The result is <b>{item.a.toLocaleString("en-US")}</b>.</p><button className="primary" onClick={()=>onChange({...state,step:state.step+1,draft:"",phase:"QUESTION"})}>Continue</button></div></>;
 const submit=()=>{if(correct)onChange({...state,step:state.step+1,draft:"",phase:"QUESTION",answers:{...state.answers,[key]:state.draft},signals:[...state.signals,{skillId:"arithmetic-accuracy",quality:2}]});else if(count===0)onChange({...state,attempts:{...state.attempts,[key]:1},draft:""});else onChange({...state,phase:"FEEDBACK",answers:{...state.answers,[key]:state.draft},signals:[...state.signals,{skillId:"arithmetic-accuracy",quality:0,hinted:true}]});};
 return <><Stage title="Calculate"><span className="calc-count">Step {state.step+1} of 4</span>{item.q}</Stage>{count>0&&<div className="inline-hint"><b>Try once more.</b> {item.h} The answer is shown after this attempt.</div>}<div className="welcome-question"><label>Your answer<input inputMode="decimal" value={state.draft} onChange={e=>onChange({...state,draft:e.target.value})}/></label><button className="primary" disabled={!state.draft.trim()} onClick={submit}>Check answer</button></div>{count>0&&state.attempts[key]>1&&<p>{money(item.a)}</p>}</>;
}

function Exhibit({state,onChange,onNext}:{state:WelcomeCaseState;onChange:(s:WelcomeCaseState)=>void;onNext:()=>void}){const kind=state.step===0?"observation":"exhibit-implication";const prompt=state.step===0?"What is the most important observation?":"Why does that matter for our recommendation?";const submit=()=>onChange({...state,phase:"FEEDBACK",answers:{...state.answers,[kind]:state.draft},signals:[...state.signals,{skillId:"exhibit-interpretation",quality:assessWelcomeResponse(kind,state.draft)}]});return <><Stage title="Read the Exhibit">Existing Northstar stores — annual operating profit by location type</Stage><div className="bar-chart" role="img" aria-label="Residential 240 thousand dollars, mixed-use 310 thousand, downtown 390 thousand, proposed downtown 350 thousand">{[["Residential neighborhood",240],["Mixed-use district",310],["Downtown business district",390],["Proposed downtown store",350]].map(([label,value])=><div key={label}><span>{label}</span><i style={{width:`${Number(value)/4}%`}}/><b>${value}K</b></div>)}</div>{state.phase==="QUESTION"?<Response label={prompt} value={state.draft} onChange={v=>onChange({...state,draft:v})} onSubmit={submit}/>:<div className="welcome-feedback"><strong><Check size={17}/>{state.step===0?"Observation":"Implication"}</strong><p>{state.step===0?"Downtown locations are Northstar’s most profitable type. The proposed store is below, but reasonably close to, the $390K downtown benchmark.":"The comparable stores make the $350K forecast more credible. But the proposed site depends heavily on office-worker traffic, and nearby office occupancy remains volatile."}</p><button className="primary" onClick={()=>state.step===0?onChange({...state,step:1,phase:"QUESTION",draft:""}):onNext()}>Continue</button></div>}</>}
function Debrief({state,onFinish}:{state:WelcomeCaseState;onFinish:()=>void}){return <><Stage title="You just completed a case.">Every case is different, but the reasoning pattern you just used appears again and again.</Stage><ol className="case-map">{["Clarify the decision","Structure the problem","Prioritize","Analyze","Calculate","Interpret","Synthesize","Recommend"].map((x,i)=><li key={x}><span>{i+1}</span>{x}</li>)}</ol><section className="noticed"><p className="kicker">What we noticed</p>{welcomeObservations(state.signals).map(x=><div key={x.label}><strong>{x.label}</strong><p>{x.text}</p></div>)}</section><button className="primary finish-case" onClick={onFinish}>Continue to Story Mode <ArrowRight size={17}/></button></>}
